// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg we;
    reg [4:0] waddr;
    reg [31:0] wdata;
    reg [4:0] raddr1;
    reg [4:0] raddr2;
    wire [31:0] rdata1;
    reg [31:0] e_rdata1, m_rdata1;
    wire [31:0] rdata2;
    reg [31:0] e_rdata2, m_rdata2;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    regfile dut (.clk(clk), .we(we), .waddr(waddr), .wdata(wdata), .raddr1(raddr1), .raddr2(raddr2), .rdata1(rdata1), .rdata2(rdata2));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "write then read";
            1: tb_gname = "fill all 31 registers";
            2: tb_gname = "write-first bypass on the same edge";
            3: tb_gname = "x0 is hardwired to zero";
            4: tb_gname = "3000 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((rdata1 ^ e_rdata1) & m_rdata1) !== 0) ||
                (((rdata2 ^ e_rdata2) & m_rdata2) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): we=%h waddr=%h wdata=%h raddr1=%h raddr2=%h -> expected rdata1=%h rdata2=%h, got rdata1=%h rdata2=%h",
                             tb_vec, $time, we, waddr, wdata, raddr1, raddr2, e_rdata1, e_rdata2, rdata1, rdata2);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h\n", tb_grp, we, waddr, wdata, raddr1, raddr2, e_rdata1, m_rdata1, e_rdata2, m_rdata2) == 10) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3072)
            $display("FAIL: testbench read %0d of 3072 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #31720;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
