// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg [7:0] a;
    reg [7:0] b;
    reg sub;
    wire [7:0] y;
    reg [7:0] e_y, m_y;
    wire carry;
    reg e_carry, m_carry;
    wire ovf;
    reg e_ovf, m_ovf;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    addsub_flags dut (.a(a), .b(b), .sub(sub), .y(y), .carry(carry), .ovf(ovf));

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "add: all corner pairs";
            1: tb_gname = "subtract: all corner pairs";
            2: tb_gname = "3000 random operations";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((y ^ e_y) & m_y) !== 0) ||
                (((carry ^ e_carry) & m_carry) !== 0) ||
                (((ovf ^ e_ovf) & m_ovf) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): a=%h b=%h sub=%h -> expected y=%h carry=%h ovf=%h, got y=%h carry=%h ovf=%h",
                             tb_vec, $time, a, b, sub, e_y, e_carry, e_ovf, y, carry, ovf);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        #1;
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h\n", tb_grp, a, b, sub, e_y, m_y, e_carry, m_carry, e_ovf, m_ovf) == 10) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            #5;
            tb_check;
            #5;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3128)
            $display("FAIL: testbench read %0d of 3128 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #32280;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
