// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    logic clk = 1'b0;
    logic rst = 1'b1;
    logic [3:0] cnt = '0;
    int trace;

    chk_gray dut (.clk(clk), .rst(rst), .cnt(cnt));

    always #5 clk = ~clk;

    initial begin
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        if (!$value$plusargs("trace=%d", trace)) trace = 0;
        case (trace)
            0: begin
                @(negedge clk); rst = 1'd1; cnt = 4'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); cnt = 4'd1;
                @(negedge clk); cnt = 4'd3;
                @(negedge clk); cnt = 4'd2;
                @(negedge clk); cnt = 4'd6;
                @(negedge clk); cnt = 4'd7;
                @(negedge clk); cnt = 4'd5;
                @(negedge clk); cnt = 4'd4;
            end
            1: begin
                @(negedge clk); rst = 1'd1; cnt = 4'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); cnt = 4'd1;
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); cnt = 4'd3;
            end
            2: begin
                @(negedge clk); rst = 1'd1; cnt = 4'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); cnt = 4'd1;
                @(negedge clk); cnt = 4'd2;
            end
            3: begin
                @(negedge clk); rst = 1'd1; cnt = 4'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); cnt = 4'd1;
                @(negedge clk); cnt = 4'd3;
                @(negedge clk); cnt = 4'd2;
                @(negedge clk); cnt = 4'd13;
                @(negedge clk); 
            end
            default: ;
        endcase
        repeat (3) @(negedge clk);
        $display("TRACE_DONE");
        $finish;
    end
endmodule
