// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg [7:0] irq_in;
    reg mask_we;
    reg [7:0] mask_data;
    reg ack;
    wire irq;
    reg e_irq, m_irq;
    wire [2:0] id;
    reg [2:0] e_id, m_id;
    wire [7:0] pending;
    reg [7:0] e_pending, m_pending;
    wire [7:0] mask;
    reg [7:0] e_mask, m_mask;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    irq_ctrl dut (.clk(clk), .rst(rst), .irq_in(irq_in), .mask_we(mask_we), .mask_data(mask_data), .ack(ack), .irq(irq), .id(id), .pending(pending), .mask(mask));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "edge sets pending";
            1: tb_gname = "priority and ack";
            2: tb_gname = "masked sources still latch";
            3: tb_gname = "3000 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((irq ^ e_irq) & m_irq) !== 0) ||
                (((id ^ e_id) & m_id) !== 0) ||
                (((pending ^ e_pending) & m_pending) !== 0) ||
                (((mask ^ e_mask) & m_mask) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h irq_in=%h mask_we=%h mask_data=%h ack=%h -> expected irq=%h id=%h pending=%h mask=%h, got irq=%h id=%h pending=%h mask=%h",
                             tb_vec, $time, rst, irq_in, mask_we, mask_data, ack, e_irq, e_id, e_pending, e_mask, irq, id, pending, mask);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, irq_in, mask_we, mask_data, ack, e_irq, m_irq, e_id, m_id, e_pending, m_pending, e_mask, m_mask) == 14) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3011)
            $display("FAIL: testbench read %0d of 3011 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #31110;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
