-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal clk : std_logic := '0';
    signal rst : std_logic := '0';
    signal irq_in : std_logic_vector(7 downto 0) := (others => '0');
    signal mask_we : std_logic := '0';
    signal mask_data : std_logic_vector(7 downto 0) := (others => '0');
    signal ack : std_logic := '0';
    signal irq : std_logic;
    signal id : std_logic_vector(2 downto 0);
    signal pending : std_logic_vector(7 downto 0);
    signal mask : std_logic_vector(7 downto 0);
    signal tb_done : boolean := false;
begin
    dut : entity work.irq_ctrl
        port map (clk => clk, rst => rst, irq_in => irq_in, mask_we => mask_we, mask_data => mask_data, ack => ack, irq => irq, id => id, pending => pending, mask => mask);

    clk <= not clk after 5 ns when not tb_done;

    watchdog : process
    begin
        wait for 31110 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_rst : std_logic_vector(0 downto 0);
        variable v_irq_in : std_logic_vector(7 downto 0);
        variable v_mask_we : std_logic_vector(0 downto 0);
        variable v_mask_data : std_logic_vector(7 downto 0);
        variable v_ack : std_logic_vector(0 downto 0);
        variable e_irq, m_irq : std_logic_vector(0 downto 0);
        variable e_id, m_id : std_logic_vector(2 downto 0);
        variable e_pending, m_pending : std_logic_vector(7 downto 0);
        variable e_mask, m_mask : std_logic_vector(7 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "edge sets pending";
                when 1 => return "priority and ack";
                when 2 => return "masked sources still latch";
                when 3 => return "3000 random cycles";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait until falling_edge(clk);
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_rst);
            hread(tb_l, v_irq_in);
            hread(tb_l, v_mask_we);
            hread(tb_l, v_mask_data);
            hread(tb_l, v_ack);
            hread(tb_l, e_irq);
            hread(tb_l, m_irq);
            hread(tb_l, e_id);
            hread(tb_l, m_id);
            hread(tb_l, e_pending);
            hread(tb_l, m_pending);
            hread(tb_l, e_mask);
            hread(tb_l, m_mask);
            rst <= v_rst(0);
            irq_in <= v_irq_in;
            mask_we <= v_mask_we(0);
            mask_data <= v_mask_data;
            ack <= v_ack(0);
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait until falling_edge(clk);
            tb_bad := tb_diff(sv(irq), e_irq, m_irq)
                   or tb_diff(sv(id), e_id, m_id)
                   or tb_diff(sv(pending), e_pending, m_pending)
                   or tb_diff(sv(mask), e_mask, m_mask);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "rst=" & to_hstring(v_rst) & " " & "irq_in=" & to_hstring(v_irq_in) & " " & "mask_we=" & to_hstring(v_mask_we) & " " & "mask_data=" & to_hstring(v_mask_data) & " " & "ack=" & to_hstring(v_ack) &
                        " -> expected " & "irq=" & to_hstring(e_irq) & " " & "id=" & to_hstring(e_id) & " " & "pending=" & to_hstring(e_pending) & " " & "mask=" & to_hstring(e_mask) &
                        ", got " & "irq=" & to_hstring(sv(irq)) & " " & "id=" & to_hstring(sv(id)) & " " & "pending=" & to_hstring(sv(pending)) & " " & "mask=" & to_hstring(sv(mask)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 3011 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 3011 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
