// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg ren_valid;
    reg [2:0] rs1;
    reg [2:0] rs2;
    reg [2:0] rd;
    reg has_rd;
    reg free_valid;
    reg [3:0] free_preg;
    wire ren_ok;
    reg e_ren_ok, m_ren_ok;
    wire stall;
    reg e_stall, m_stall;
    wire [3:0] ps1;
    reg [3:0] e_ps1, m_ps1;
    wire [3:0] ps2;
    reg [3:0] e_ps2, m_ps2;
    wire [3:0] pd;
    reg [3:0] e_pd, m_pd;
    wire [3:0] old_pd;
    reg [3:0] e_old_pd, m_old_pd;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    rename dut (.clk(clk), .rst(rst), .ren_valid(ren_valid), .rs1(rs1), .rs2(rs2), .rd(rd), .has_rd(has_rd), .free_valid(free_valid), .free_preg(free_preg), .ren_ok(ren_ok), .stall(stall), .ps1(ps1), .ps2(ps2), .pd(pd), .old_pd(old_pd));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "reset";
            1: tb_gname = "first renames";
            2: tb_gname = "dependency chain through the RAT";
            3: tb_gname = "instruction without a destination";
            4: tb_gname = "free list exhaustion stalls";
            5: tb_gname = "freed register is reused next cycle";
            6: tb_gname = "3000 random rename / free cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((ren_ok ^ e_ren_ok) & m_ren_ok) !== 0) ||
                (((stall ^ e_stall) & m_stall) !== 0) ||
                (((ps1 ^ e_ps1) & m_ps1) !== 0) ||
                (((ps2 ^ e_ps2) & m_ps2) !== 0) ||
                (((pd ^ e_pd) & m_pd) !== 0) ||
                (((old_pd ^ e_old_pd) & m_old_pd) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h ren_valid=%h rs1=%h rs2=%h rd=%h has_rd=%h free_valid=%h free_preg=%h -> expected ren_ok=%h stall=%h ps1=%h ps2=%h pd=%h old_pd=%h, got ren_ok=%h stall=%h ps1=%h ps2=%h pd=%h old_pd=%h",
                             tb_vec, $time, rst, ren_valid, rs1, rs2, rd, has_rd, free_valid, free_preg, e_ren_ok, e_stall, e_ps1, e_ps2, e_pd, e_old_pd, ren_ok, stall, ps1, ps2, pd, old_pd);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, ren_valid, rs1, rs2, rd, has_rd, free_valid, free_preg, e_ren_ok, m_ren_ok, e_stall, m_stall, e_ps1, m_ps1, e_ps2, m_ps2, e_pd, m_pd, e_old_pd, m_old_pd) == 21) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3014)
            $display("FAIL: testbench read %0d of 3014 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #31140;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
