// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg pclk = 1'b0;
    reg presetn;
    reg psel;
    reg penable;
    reg pwrite;
    reg [3:0] paddr;
    reg [31:0] pwdata;
    wire [31:0] prdata;
    reg [31:0] e_prdata, m_prdata;
    wire pready;
    reg e_pready, m_pready;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    apb_regs dut (.pclk(pclk), .presetn(presetn), .psel(psel), .penable(penable), .pwrite(pwrite), .paddr(paddr), .pwdata(pwdata), .prdata(prdata), .pready(pready));

    always #5 pclk = ~pclk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "reset values";
            1: tb_gname = "write then read back";
            2: tb_gname = "read-only ID register";
            3: tb_gname = "600 random transfers";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((prdata ^ e_prdata) & m_prdata) !== 0) ||
                (((pready ^ e_pready) & m_pready) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): presetn=%h psel=%h penable=%h pwrite=%h paddr=%h pwdata=%h -> expected prdata=%h pready=%h, got prdata=%h pready=%h",
                             tb_vec, $time, presetn, psel, penable, pwrite, paddr, pwdata, e_prdata, e_pready, prdata, pready);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge pclk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h\n", tb_grp, presetn, psel, penable, pwrite, paddr, pwdata, e_prdata, m_prdata, e_pready, m_pready) == 11) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge pclk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 1407)
            $display("FAIL: testbench read %0d of 1407 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #15070;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
