// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg req;
    reg [7:0] data_in;
    wire ack;
    reg e_ack, m_ack;
    wire [7:0] data_out;
    reg [7:0] e_data_out, m_data_out;
    wire strobe;
    reg e_strobe, m_strobe;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    req_ack_rx dut (.clk(clk), .rst(rst), .req(req), .data_in(data_in), .ack(ack), .data_out(data_out), .strobe(strobe));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "single transfer";
            1: tb_gname = "data captured on req rise";
            2: tb_gname = "2000 cycles of random transfers";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((ack ^ e_ack) & m_ack) !== 0) ||
                (((data_out ^ e_data_out) & m_data_out) !== 0) ||
                (((strobe ^ e_strobe) & m_strobe) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h req=%h data_in=%h -> expected ack=%h data_out=%h strobe=%h, got ack=%h data_out=%h strobe=%h",
                             tb_vec, $time, rst, req, data_in, e_ack, e_data_out, e_strobe, ack, data_out, strobe);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, req, data_in, e_ack, m_ack, e_data_out, m_data_out, e_strobe, m_strobe) == 10) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 2014)
            $display("FAIL: testbench read %0d of 2014 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #21140;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
