// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg [7:0] in0;
    reg [7:0] in1;
    reg [7:0] in2;
    reg [7:0] in3;
    wire [7:0] out0;
    reg [7:0] e_out0, m_out0;
    wire [7:0] out1;
    reg [7:0] e_out1, m_out1;
    wire [7:0] out2;
    reg [7:0] e_out2, m_out2;
    wire [7:0] out3;
    reg [7:0] e_out3, m_out3;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    sort4 dut (.in0(in0), .in1(in1), .in2(in2), .in3(in3), .out0(out0), .out1(out1), .out2(out2), .out3(out3));

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "sorts";
            1: tb_gname = "all permutations";
            2: tb_gname = "5000 random";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((out0 ^ e_out0) & m_out0) !== 0) ||
                (((out1 ^ e_out1) & m_out1) !== 0) ||
                (((out2 ^ e_out2) & m_out2) !== 0) ||
                (((out3 ^ e_out3) & m_out3) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): in0=%h in1=%h in2=%h in3=%h -> expected out0=%h out1=%h out2=%h out3=%h, got out0=%h out1=%h out2=%h out3=%h",
                             tb_vec, $time, in0, in1, in2, in3, e_out0, e_out1, e_out2, e_out3, out0, out1, out2, out3);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        #1;
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, in0, in1, in2, in3, e_out0, m_out0, e_out1, m_out1, e_out2, m_out2, e_out3, m_out3) == 13) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            #5;
            tb_check;
            #5;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 5029)
            $display("FAIL: testbench read %0d of 5029 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #51290;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
