-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal in0 : std_logic_vector(7 downto 0) := (others => '0');
    signal in1 : std_logic_vector(7 downto 0) := (others => '0');
    signal in2 : std_logic_vector(7 downto 0) := (others => '0');
    signal in3 : std_logic_vector(7 downto 0) := (others => '0');
    signal out0 : std_logic_vector(7 downto 0);
    signal out1 : std_logic_vector(7 downto 0);
    signal out2 : std_logic_vector(7 downto 0);
    signal out3 : std_logic_vector(7 downto 0);
    signal tb_done : boolean := false;
begin
    dut : entity work.sort4
        port map (in0 => in0, in1 => in1, in2 => in2, in3 => in3, out0 => out0, out1 => out1, out2 => out2, out3 => out3);

    watchdog : process
    begin
        wait for 51290 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_in0 : std_logic_vector(7 downto 0);
        variable v_in1 : std_logic_vector(7 downto 0);
        variable v_in2 : std_logic_vector(7 downto 0);
        variable v_in3 : std_logic_vector(7 downto 0);
        variable e_out0, m_out0 : std_logic_vector(7 downto 0);
        variable e_out1, m_out1 : std_logic_vector(7 downto 0);
        variable e_out2, m_out2 : std_logic_vector(7 downto 0);
        variable e_out3, m_out3 : std_logic_vector(7 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "sorts";
                when 1 => return "all permutations";
                when 2 => return "5000 random";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait for 1 ns;
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_in0);
            hread(tb_l, v_in1);
            hread(tb_l, v_in2);
            hread(tb_l, v_in3);
            hread(tb_l, e_out0);
            hread(tb_l, m_out0);
            hread(tb_l, e_out1);
            hread(tb_l, m_out1);
            hread(tb_l, e_out2);
            hread(tb_l, m_out2);
            hread(tb_l, e_out3);
            hread(tb_l, m_out3);
            in0 <= v_in0;
            in1 <= v_in1;
            in2 <= v_in2;
            in3 <= v_in3;
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait for 5 ns;
            tb_bad := tb_diff(sv(out0), e_out0, m_out0)
                   or tb_diff(sv(out1), e_out1, m_out1)
                   or tb_diff(sv(out2), e_out2, m_out2)
                   or tb_diff(sv(out3), e_out3, m_out3);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "in0=" & to_hstring(v_in0) & " " & "in1=" & to_hstring(v_in1) & " " & "in2=" & to_hstring(v_in2) & " " & "in3=" & to_hstring(v_in3) &
                        " -> expected " & "out0=" & to_hstring(e_out0) & " " & "out1=" & to_hstring(e_out1) & " " & "out2=" & to_hstring(e_out2) & " " & "out3=" & to_hstring(e_out3) &
                        ", got " & "out0=" & to_hstring(sv(out0)) & " " & "out1=" & to_hstring(sv(out1)) & " " & "out2=" & to_hstring(sv(out2)) & " " & "out3=" & to_hstring(sv(out3)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
            wait for 5 ns;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 5029 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 5029 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
