-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal clk : std_logic := '0';
    signal rst : std_logic := '0';
    signal start : std_logic := '0';
    signal tx_data : std_logic_vector(7 downto 0) := (others => '0');
    signal miso : std_logic := '0';
    signal sclk : std_logic;
    signal mosi : std_logic;
    signal cs_n : std_logic;
    signal busy : std_logic;
    signal done : std_logic;
    signal rx_data : std_logic_vector(7 downto 0);
    signal tb_done : boolean := false;
begin
    dut : entity work.spi_master
        port map (clk => clk, rst => rst, start => start, tx_data => tx_data, miso => miso, sclk => sclk, mosi => mosi, cs_n => cs_n, busy => busy, done => done, rx_data => rx_data);

    clk <= not clk after 5 ns when not tb_done;

    watchdog : process
    begin
        wait for 41720 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_rst : std_logic_vector(0 downto 0);
        variable v_start : std_logic_vector(0 downto 0);
        variable v_tx_data : std_logic_vector(7 downto 0);
        variable v_miso : std_logic_vector(0 downto 0);
        variable e_sclk, m_sclk : std_logic_vector(0 downto 0);
        variable e_mosi, m_mosi : std_logic_vector(0 downto 0);
        variable e_cs_n, m_cs_n : std_logic_vector(0 downto 0);
        variable e_busy, m_busy : std_logic_vector(0 downto 0);
        variable e_done, m_done : std_logic_vector(0 downto 0);
        variable e_rx_data, m_rx_data : std_logic_vector(7 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "full-duplex byte";
                when 1 => return "start while busy is ignored";
                when 2 => return "4000 random cycles";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait until falling_edge(clk);
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_rst);
            hread(tb_l, v_start);
            hread(tb_l, v_tx_data);
            hread(tb_l, v_miso);
            hread(tb_l, e_sclk);
            hread(tb_l, m_sclk);
            hread(tb_l, e_mosi);
            hread(tb_l, m_mosi);
            hread(tb_l, e_cs_n);
            hread(tb_l, m_cs_n);
            hread(tb_l, e_busy);
            hread(tb_l, m_busy);
            hread(tb_l, e_done);
            hread(tb_l, m_done);
            hread(tb_l, e_rx_data);
            hread(tb_l, m_rx_data);
            rst <= v_rst(0);
            start <= v_start(0);
            tx_data <= v_tx_data;
            miso <= v_miso(0);
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait until falling_edge(clk);
            tb_bad := tb_diff(sv(sclk), e_sclk, m_sclk)
                   or tb_diff(sv(mosi), e_mosi, m_mosi)
                   or tb_diff(sv(cs_n), e_cs_n, m_cs_n)
                   or tb_diff(sv(busy), e_busy, m_busy)
                   or tb_diff(sv(done), e_done, m_done)
                   or tb_diff(sv(rx_data), e_rx_data, m_rx_data);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "rst=" & to_hstring(v_rst) & " " & "start=" & to_hstring(v_start) & " " & "tx_data=" & to_hstring(v_tx_data) & " " & "miso=" & to_hstring(v_miso) &
                        " -> expected " & "sclk=" & to_hstring(e_sclk) & " " & "mosi=" & to_hstring(e_mosi) & " " & "cs_n=" & to_hstring(e_cs_n) & " " & "busy=" & to_hstring(e_busy) & " " & "done=" & to_hstring(e_done) & " " & "rx_data=" & to_hstring(e_rx_data) &
                        ", got " & "sclk=" & to_hstring(sv(sclk)) & " " & "mosi=" & to_hstring(sv(mosi)) & " " & "cs_n=" & to_hstring(sv(cs_n)) & " " & "busy=" & to_hstring(sv(busy)) & " " & "done=" & to_hstring(sv(done)) & " " & "rx_data=" & to_hstring(sv(rx_data)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 4072 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 4072 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
