// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg [7:0] active;
    reg [7:0] cond;
    wire [7:0] taken;
    reg [7:0] e_taken, m_taken;
    wire [7:0] not_taken;
    reg [7:0] e_not_taken, m_not_taken;
    wire divergent;
    reg e_divergent, m_divergent;
    wire [2:0] first_lane;
    reg [2:0] e_first_lane, m_first_lane;
    wire any_active;
    reg e_any_active, m_any_active;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    thread_mask dut (.active(active), .cond(cond), .taken(taken), .not_taken(not_taken), .divergent(divergent), .first_lane(first_lane), .any_active(any_active));

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "divergent branch";
            1: tb_gname = "uniform branch";
            2: tb_gname = "empty warp";
            3: tb_gname = "first active lane at every position";
            4: tb_gname = "1500 random warps";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((taken ^ e_taken) & m_taken) !== 0) ||
                (((not_taken ^ e_not_taken) & m_not_taken) !== 0) ||
                (((divergent ^ e_divergent) & m_divergent) !== 0) ||
                (((first_lane ^ e_first_lane) & m_first_lane) !== 0) ||
                (((any_active ^ e_any_active) & m_any_active) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): active=%h cond=%h -> expected taken=%h not_taken=%h divergent=%h first_lane=%h any_active=%h, got taken=%h not_taken=%h divergent=%h first_lane=%h any_active=%h",
                             tb_vec, $time, active, cond, e_taken, e_not_taken, e_divergent, e_first_lane, e_any_active, taken, not_taken, divergent, first_lane, any_active);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        #1;
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, active, cond, e_taken, m_taken, e_not_taken, m_not_taken, e_divergent, m_divergent, e_first_lane, m_first_lane, e_any_active, m_any_active) == 13) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            #5;
            tb_check;
            #5;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 1520)
            $display("FAIL: testbench read %0d of 1520 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #16200;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
