-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal active : std_logic_vector(7 downto 0) := (others => '0');
    signal cond : std_logic_vector(7 downto 0) := (others => '0');
    signal taken : std_logic_vector(7 downto 0);
    signal not_taken : std_logic_vector(7 downto 0);
    signal divergent : std_logic;
    signal first_lane : std_logic_vector(2 downto 0);
    signal any_active : std_logic;
    signal tb_done : boolean := false;
begin
    dut : entity work.thread_mask
        port map (active => active, cond => cond, taken => taken, not_taken => not_taken, divergent => divergent, first_lane => first_lane, any_active => any_active);

    watchdog : process
    begin
        wait for 16200 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_active : std_logic_vector(7 downto 0);
        variable v_cond : std_logic_vector(7 downto 0);
        variable e_taken, m_taken : std_logic_vector(7 downto 0);
        variable e_not_taken, m_not_taken : std_logic_vector(7 downto 0);
        variable e_divergent, m_divergent : std_logic_vector(0 downto 0);
        variable e_first_lane, m_first_lane : std_logic_vector(2 downto 0);
        variable e_any_active, m_any_active : std_logic_vector(0 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "divergent branch";
                when 1 => return "uniform branch";
                when 2 => return "empty warp";
                when 3 => return "first active lane at every position";
                when 4 => return "1500 random warps";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait for 1 ns;
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_active);
            hread(tb_l, v_cond);
            hread(tb_l, e_taken);
            hread(tb_l, m_taken);
            hread(tb_l, e_not_taken);
            hread(tb_l, m_not_taken);
            hread(tb_l, e_divergent);
            hread(tb_l, m_divergent);
            hread(tb_l, e_first_lane);
            hread(tb_l, m_first_lane);
            hread(tb_l, e_any_active);
            hread(tb_l, m_any_active);
            active <= v_active;
            cond <= v_cond;
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait for 5 ns;
            tb_bad := tb_diff(sv(taken), e_taken, m_taken)
                   or tb_diff(sv(not_taken), e_not_taken, m_not_taken)
                   or tb_diff(sv(divergent), e_divergent, m_divergent)
                   or tb_diff(sv(first_lane), e_first_lane, m_first_lane)
                   or tb_diff(sv(any_active), e_any_active, m_any_active);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "active=" & to_hstring(v_active) & " " & "cond=" & to_hstring(v_cond) &
                        " -> expected " & "taken=" & to_hstring(e_taken) & " " & "not_taken=" & to_hstring(e_not_taken) & " " & "divergent=" & to_hstring(e_divergent) & " " & "first_lane=" & to_hstring(e_first_lane) & " " & "any_active=" & to_hstring(e_any_active) &
                        ", got " & "taken=" & to_hstring(sv(taken)) & " " & "not_taken=" & to_hstring(sv(not_taken)) & " " & "divergent=" & to_hstring(sv(divergent)) & " " & "first_lane=" & to_hstring(sv(first_lane)) & " " & "any_active=" & to_hstring(sv(any_active)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
            wait for 5 ns;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 1520 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 1520 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
