// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg miss;
    reg dirty;
    reg [7:0] miss_line;
    reg [7:0] victim_line;
    reg mem_ack;
    wire mem_req;
    reg e_mem_req, m_mem_req;
    wire mem_we;
    reg e_mem_we, m_mem_we;
    wire [9:0] mem_addr;
    reg [9:0] e_mem_addr, m_mem_addr;
    wire done;
    reg e_done, m_done;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    refill_fsm dut (.clk(clk), .rst(rst), .miss(miss), .dirty(dirty), .miss_line(miss_line), .victim_line(victim_line), .mem_ack(mem_ack), .mem_req(mem_req), .mem_we(mem_we), .mem_addr(mem_addr), .done(done));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "reset";
            1: tb_gname = "clean miss: refill only";
            2: tb_gname = "dirty miss: write back, then refill";
            3: tb_gname = "slow memory with wait states";
            4: tb_gname = "3000 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((mem_req ^ e_mem_req) & m_mem_req) !== 0) ||
                (((mem_we ^ e_mem_we) & m_mem_we) !== 0) ||
                (((mem_addr ^ e_mem_addr) & m_mem_addr) !== 0) ||
                (((done ^ e_done) & m_done) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h miss=%h dirty=%h miss_line=%h victim_line=%h mem_ack=%h -> expected mem_req=%h mem_we=%h mem_addr=%h done=%h, got mem_req=%h mem_we=%h mem_addr=%h done=%h",
                             tb_vec, $time, rst, miss, dirty, miss_line, victim_line, mem_ack, e_mem_req, e_mem_we, e_mem_addr, e_done, mem_req, mem_we, mem_addr, done);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, miss, dirty, miss_line, victim_line, mem_ack, e_mem_req, m_mem_req, e_mem_we, m_mem_we, e_mem_addr, m_mem_addr, e_done, m_done) == 15) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3053)
            $display("FAIL: testbench read %0d of 3053 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #31530;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
