// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg [1:0] op;
    reg [2:0] index;
    wire [7:0] valid;
    reg [7:0] e_valid, m_valid;
    wire [7:0] dirty;
    reg [7:0] e_dirty, m_dirty;
    wire writeback;
    reg e_writeback, m_writeback;
    wire [2:0] wb_index;
    reg [2:0] e_wb_index, m_wb_index;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    dirty_tracker dut (.clk(clk), .rst(rst), .op(op), .index(index), .valid(valid), .dirty(dirty), .writeback(writeback), .wb_index(wb_index));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "reset";
            1: tb_gname = "write marks dirty";
            2: tb_gname = "fill of a dirty line writes back";
            3: tb_gname = "clean lines are dropped silently";
            4: tb_gname = "2500 random operations";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((valid ^ e_valid) & m_valid) !== 0) ||
                (((dirty ^ e_dirty) & m_dirty) !== 0) ||
                (((writeback ^ e_writeback) & m_writeback) !== 0) ||
                (((wb_index ^ e_wb_index) & m_wb_index) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h op=%h index=%h -> expected valid=%h dirty=%h writeback=%h wb_index=%h, got valid=%h dirty=%h writeback=%h wb_index=%h",
                             tb_vec, $time, rst, op, index, e_valid, e_dirty, e_writeback, e_wb_index, valid, dirty, writeback, wb_index);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, op, index, e_valid, m_valid, e_dirty, m_dirty, e_writeback, m_writeback, e_wb_index, m_wb_index) == 12) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 2509)
            $display("FAIL: testbench read %0d of 2509 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #26090;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
