// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg we;
    reg [1:0] addr;
    reg [7:0] wdata;
    reg [7:0] gpio_in;
    wire [7:0] rdata;
    reg [7:0] e_rdata, m_rdata;
    wire [7:0] gpio_out;
    reg [7:0] e_gpio_out, m_gpio_out;
    wire [7:0] gpio_oe;
    reg [7:0] e_gpio_oe, m_gpio_oe;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    mmio_gpio dut (.clk(clk), .rst(rst), .we(we), .addr(addr), .wdata(wdata), .gpio_in(gpio_in), .rdata(rdata), .gpio_out(gpio_out), .gpio_oe(gpio_oe));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "OUT and DIR registers";
            1: tb_gname = "IN is read-only";
            2: tb_gname = "input synchronizer latency";
            3: tb_gname = "sticky rise flags, write-1-to-clear";
            4: tb_gname = "3000 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((rdata ^ e_rdata) & m_rdata) !== 0) ||
                (((gpio_out ^ e_gpio_out) & m_gpio_out) !== 0) ||
                (((gpio_oe ^ e_gpio_oe) & m_gpio_oe) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h we=%h addr=%h wdata=%h gpio_in=%h -> expected rdata=%h gpio_out=%h gpio_oe=%h, got rdata=%h gpio_out=%h gpio_oe=%h",
                             tb_vec, $time, rst, we, addr, wdata, gpio_in, e_rdata, e_gpio_out, e_gpio_oe, rdata, gpio_out, gpio_oe);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, we, addr, wdata, gpio_in, e_rdata, m_rdata, e_gpio_out, m_gpio_out, e_gpio_oe, m_gpio_oe) == 12) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3020)
            $display("FAIL: testbench read %0d of 3020 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #31200;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
