// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg [2:0] req;
    reg [2:0] lock;
    wire [2:0] gnt;
    reg [2:0] e_gnt, m_gnt;
    wire [1:0] owner;
    reg [1:0] e_owner, m_owner;
    wire busy;
    reg e_busy, m_busy;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    bus_arb dut (.clk(clk), .rst(rst), .req(req), .lock(lock), .gnt(gnt), .owner(owner), .busy(busy));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "fixed priority";
            1: tb_gname = "lock holds the bus";
            2: tb_gname = "release";
            3: tb_gname = "lock without request is ignored";
            4: tb_gname = "2500 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((gnt ^ e_gnt) & m_gnt) !== 0) ||
                (((owner ^ e_owner) & m_owner) !== 0) ||
                (((busy ^ e_busy) & m_busy) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h req=%h lock=%h -> expected gnt=%h owner=%h busy=%h, got gnt=%h owner=%h busy=%h",
                             tb_vec, $time, rst, req, lock, e_gnt, e_owner, e_busy, gnt, owner, busy);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, req, lock, e_gnt, m_gnt, e_owner, m_owner, e_busy, m_busy) == 10) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 2512)
            $display("FAIL: testbench read %0d of 2512 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #26120;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
