// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    logic clk = 1'b0;
    logic rst = 1'b1;
    logic [3:0] state = '0;
    int trace;

    chk_onehot dut (.clk(clk), .rst(rst), .state(state));

    always #5 clk = ~clk;

    initial begin
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        if (!$value$plusargs("trace=%d", trace)) trace = 0;
        case (trace)
            0: begin
                @(negedge clk); rst = 1'd1; state = 4'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0; state = 4'd1;
                @(negedge clk); state = 4'd2;
                @(negedge clk); state = 4'd4;
                @(negedge clk); state = 4'd8;
                @(negedge clk); state = 4'd1;
                @(negedge clk); 
            end
            1: begin
                @(negedge clk); rst = 1'd1; state = 4'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0; state = 4'd1;
                @(negedge clk); state = 4'd2;
                @(negedge clk); state = 4'd0;
                @(negedge clk); state = 4'd4;
            end
            2: begin
                @(negedge clk); rst = 1'd1; state = 4'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0; state = 4'd1;
                @(negedge clk); state = 4'd3;
                @(negedge clk); state = 4'd2;
            end
            3: begin
                @(negedge clk); rst = 1'd1; state = 4'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0; state = 4'd8;
                @(negedge clk); 
                @(negedge clk); state = 4'd15;
                @(negedge clk); state = 4'd8;
            end
            default: ;
        endcase
        repeat (3) @(negedge clk);
        $display("TRACE_DONE");
        $finish;
    end
endmodule
