// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg tck = 1'b0;
    reg trst;
    reg tms;
    wire [3:0] state;
    reg [3:0] e_state, m_state;
    wire shift_dr;
    reg e_shift_dr, m_shift_dr;
    wire shift_ir;
    reg e_shift_ir, m_shift_ir;
    wire capture_dr;
    reg e_capture_dr, m_capture_dr;
    wire update_dr;
    reg e_update_dr, m_update_dr;
    wire tlr;
    reg e_tlr, m_tlr;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    jtag_tap dut (.tck(tck), .trst(trst), .tms(tms), .state(state), .shift_dr(shift_dr), .shift_ir(shift_ir), .capture_dr(capture_dr), .update_dr(update_dr), .tlr(tlr));

    always #5 tck = ~tck;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "reset";
            1: tb_gname = "DR scan path";
            2: tb_gname = "IR scan path";
            3: tb_gname = "reset by TMS: five ones from every state";
            4: tb_gname = "2000 random TMS sequences";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((state ^ e_state) & m_state) !== 0) ||
                (((shift_dr ^ e_shift_dr) & m_shift_dr) !== 0) ||
                (((shift_ir ^ e_shift_ir) & m_shift_ir) !== 0) ||
                (((capture_dr ^ e_capture_dr) & m_capture_dr) !== 0) ||
                (((update_dr ^ e_update_dr) & m_update_dr) !== 0) ||
                (((tlr ^ e_tlr) & m_tlr) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): trst=%h tms=%h -> expected state=%h shift_dr=%h shift_ir=%h capture_dr=%h update_dr=%h tlr=%h, got state=%h shift_dr=%h shift_ir=%h capture_dr=%h update_dr=%h tlr=%h",
                             tb_vec, $time, trst, tms, e_state, e_shift_dr, e_shift_ir, e_capture_dr, e_update_dr, e_tlr, state, shift_dr, shift_ir, capture_dr, update_dr, tlr);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge tck);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, trst, tms, e_state, m_state, e_shift_dr, m_shift_dr, e_shift_ir, m_shift_ir, e_capture_dr, m_capture_dr, e_update_dr, m_update_dr, e_tlr, m_tlr) == 15) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge tck);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 2243)
            $display("FAIL: testbench read %0d of 2243 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #23430;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
