-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal tck : std_logic := '0';
    signal trst : std_logic := '0';
    signal tms : std_logic := '0';
    signal state : std_logic_vector(3 downto 0);
    signal shift_dr : std_logic;
    signal shift_ir : std_logic;
    signal capture_dr : std_logic;
    signal update_dr : std_logic;
    signal tlr : std_logic;
    signal tb_done : boolean := false;
begin
    dut : entity work.jtag_tap
        port map (tck => tck, trst => trst, tms => tms, state => state, shift_dr => shift_dr, shift_ir => shift_ir, capture_dr => capture_dr, update_dr => update_dr, tlr => tlr);

    tck <= not tck after 5 ns when not tb_done;

    watchdog : process
    begin
        wait for 23430 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_trst : std_logic_vector(0 downto 0);
        variable v_tms : std_logic_vector(0 downto 0);
        variable e_state, m_state : std_logic_vector(3 downto 0);
        variable e_shift_dr, m_shift_dr : std_logic_vector(0 downto 0);
        variable e_shift_ir, m_shift_ir : std_logic_vector(0 downto 0);
        variable e_capture_dr, m_capture_dr : std_logic_vector(0 downto 0);
        variable e_update_dr, m_update_dr : std_logic_vector(0 downto 0);
        variable e_tlr, m_tlr : std_logic_vector(0 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "reset";
                when 1 => return "DR scan path";
                when 2 => return "IR scan path";
                when 3 => return "reset by TMS: five ones from every state";
                when 4 => return "2000 random TMS sequences";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait until falling_edge(tck);
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_trst);
            hread(tb_l, v_tms);
            hread(tb_l, e_state);
            hread(tb_l, m_state);
            hread(tb_l, e_shift_dr);
            hread(tb_l, m_shift_dr);
            hread(tb_l, e_shift_ir);
            hread(tb_l, m_shift_ir);
            hread(tb_l, e_capture_dr);
            hread(tb_l, m_capture_dr);
            hread(tb_l, e_update_dr);
            hread(tb_l, m_update_dr);
            hread(tb_l, e_tlr);
            hread(tb_l, m_tlr);
            trst <= v_trst(0);
            tms <= v_tms(0);
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait until falling_edge(tck);
            tb_bad := tb_diff(sv(state), e_state, m_state)
                   or tb_diff(sv(shift_dr), e_shift_dr, m_shift_dr)
                   or tb_diff(sv(shift_ir), e_shift_ir, m_shift_ir)
                   or tb_diff(sv(capture_dr), e_capture_dr, m_capture_dr)
                   or tb_diff(sv(update_dr), e_update_dr, m_update_dr)
                   or tb_diff(sv(tlr), e_tlr, m_tlr);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "trst=" & to_hstring(v_trst) & " " & "tms=" & to_hstring(v_tms) &
                        " -> expected " & "state=" & to_hstring(e_state) & " " & "shift_dr=" & to_hstring(e_shift_dr) & " " & "shift_ir=" & to_hstring(e_shift_ir) & " " & "capture_dr=" & to_hstring(e_capture_dr) & " " & "update_dr=" & to_hstring(e_update_dr) & " " & "tlr=" & to_hstring(e_tlr) &
                        ", got " & "state=" & to_hstring(sv(state)) & " " & "shift_dr=" & to_hstring(sv(shift_dr)) & " " & "shift_ir=" & to_hstring(sv(shift_ir)) & " " & "capture_dr=" & to_hstring(sv(capture_dr)) & " " & "update_dr=" & to_hstring(sv(update_dr)) & " " & "tlr=" & to_hstring(sv(tlr)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 2243 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 2243 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
