// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg push;
    reg pop;
    reg [7:0] addr;
    wire [7:0] top;
    reg [7:0] e_top, m_top;
    wire [2:0] count;
    reg [2:0] e_count, m_count;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    ras4 dut (.clk(clk), .rst(rst), .push(push), .pop(pop), .addr(addr), .top(top), .count(count));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "call and return";
            1: tb_gname = "overflow keeps the newest";
            2: tb_gname = "tail call replaces the top";
            3: tb_gname = "3000 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((top ^ e_top) & m_top) !== 0) ||
                (((count ^ e_count) & m_count) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h push=%h pop=%h addr=%h -> expected top=%h count=%h, got top=%h count=%h",
                             tb_vec, $time, rst, push, pop, addr, e_top, e_count, top, count);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h\n", tb_grp, rst, push, pop, addr, e_top, m_top, e_count, m_count) == 9) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3018)
            $display("FAIL: testbench read %0d of 3018 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #31180;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
