-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal clk : std_logic := '0';
    signal rst : std_logic := '0';
    signal rd : std_logic := '0';
    signal wr : std_logic := '0';
    signal fill : std_logic := '0';
    signal inv : std_logic := '0';
    signal addr : std_logic_vector(7 downto 0) := (others => '0');
    signal wdata : std_logic_vector(7 downto 0) := (others => '0');
    signal fill_data : std_logic_vector(7 downto 0) := (others => '0');
    signal hit : std_logic;
    signal rdata : std_logic_vector(7 downto 0);
    signal hits : std_logic_vector(7 downto 0);
    signal misses : std_logic_vector(7 downto 0);
    signal tb_done : boolean := false;
begin
    dut : entity work.dm_cache
        port map (clk => clk, rst => rst, rd => rd, wr => wr, fill => fill, inv => inv, addr => addr, wdata => wdata, fill_data => fill_data, hit => hit, rdata => rdata, hits => hits, misses => misses);

    clk <= not clk after 5 ns when not tb_done;

    watchdog : process
    begin
        wait for 31170 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_rst : std_logic_vector(0 downto 0);
        variable v_rd : std_logic_vector(0 downto 0);
        variable v_wr : std_logic_vector(0 downto 0);
        variable v_fill : std_logic_vector(0 downto 0);
        variable v_inv : std_logic_vector(0 downto 0);
        variable v_addr : std_logic_vector(7 downto 0);
        variable v_wdata : std_logic_vector(7 downto 0);
        variable v_fill_data : std_logic_vector(7 downto 0);
        variable e_hit, m_hit : std_logic_vector(0 downto 0);
        variable e_rdata, m_rdata : std_logic_vector(7 downto 0);
        variable e_hits, m_hits : std_logic_vector(7 downto 0);
        variable e_misses, m_misses : std_logic_vector(7 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "cold miss then fill then hit";
                when 1 => return "conflict misses";
                when 2 => return "write-through, no allocate";
                when 3 => return "invalidate all";
                when 4 => return "3000 random operations";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait until falling_edge(clk);
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_rst);
            hread(tb_l, v_rd);
            hread(tb_l, v_wr);
            hread(tb_l, v_fill);
            hread(tb_l, v_inv);
            hread(tb_l, v_addr);
            hread(tb_l, v_wdata);
            hread(tb_l, v_fill_data);
            hread(tb_l, e_hit);
            hread(tb_l, m_hit);
            hread(tb_l, e_rdata);
            hread(tb_l, m_rdata);
            hread(tb_l, e_hits);
            hread(tb_l, m_hits);
            hread(tb_l, e_misses);
            hread(tb_l, m_misses);
            rst <= v_rst(0);
            rd <= v_rd(0);
            wr <= v_wr(0);
            fill <= v_fill(0);
            inv <= v_inv(0);
            addr <= v_addr;
            wdata <= v_wdata;
            fill_data <= v_fill_data;
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait until falling_edge(clk);
            tb_bad := tb_diff(sv(hit), e_hit, m_hit)
                   or tb_diff(sv(rdata), e_rdata, m_rdata)
                   or tb_diff(sv(hits), e_hits, m_hits)
                   or tb_diff(sv(misses), e_misses, m_misses);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "rst=" & to_hstring(v_rst) & " " & "rd=" & to_hstring(v_rd) & " " & "wr=" & to_hstring(v_wr) & " " & "fill=" & to_hstring(v_fill) & " " & "inv=" & to_hstring(v_inv) & " " & "addr=" & to_hstring(v_addr) & " " & "wdata=" & to_hstring(v_wdata) & " " & "fill_data=" & to_hstring(v_fill_data) &
                        " -> expected " & "hit=" & to_hstring(e_hit) & " " & "rdata=" & to_hstring(e_rdata) & " " & "hits=" & to_hstring(e_hits) & " " & "misses=" & to_hstring(e_misses) &
                        ", got " & "hit=" & to_hstring(sv(hit)) & " " & "rdata=" & to_hstring(sv(rdata)) & " " & "hits=" & to_hstring(sv(hits)) & " " & "misses=" & to_hstring(sv(misses)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 3017 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 3017 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
