// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg en;
    reg [7:0] din;
    reg [7:0] golden;
    wire [7:0] sig;
    reg [7:0] e_sig, m_sig;
    wire pass;
    reg e_pass, m_pass;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    misr8 dut (.clk(clk), .rst(rst), .en(en), .din(din), .golden(golden), .sig(sig), .pass(pass));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "reset seed";
            1: tb_gname = "single step";
            2: tb_gname = "hold when disabled";
            3: tb_gname = "signature compare";
            4: tb_gname = "1500 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((sig ^ e_sig) & m_sig) !== 0) ||
                (((pass ^ e_pass) & m_pass) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h en=%h din=%h golden=%h -> expected sig=%h pass=%h, got sig=%h pass=%h",
                             tb_vec, $time, rst, en, din, golden, e_sig, e_pass, sig, pass);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h\n", tb_grp, rst, en, din, golden, e_sig, m_sig, e_pass, m_pass) == 9) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 1526)
            $display("FAIL: testbench read %0d of 1526 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #16260;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
