// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg start;
    reg [15:0] x;
    wire busy;
    reg e_busy, m_busy;
    wire done;
    reg e_done, m_done;
    wire [7:0] root;
    reg [7:0] e_root, m_root;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    isqrt16 dut (.clk(clk), .rst(rst), .start(start), .x(x), .busy(busy), .done(done), .root(root));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "perfect squares";
            1: tb_gname = "largest input and non-squares";
            2: tb_gname = "start while busy is ignored";
            3: tb_gname = "3000 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((busy ^ e_busy) & m_busy) !== 0) ||
                (((done ^ e_done) & m_done) !== 0) ||
                (((root ^ e_root) & m_root) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h start=%h x=%h -> expected busy=%h done=%h root=%h, got busy=%h done=%h root=%h",
                             tb_vec, $time, rst, start, x, e_busy, e_done, e_root, busy, done, root);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, start, x, e_busy, m_busy, e_done, m_done, e_root, m_root) == 10) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3119)
            $display("FAIL: testbench read %0d of 3119 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #32190;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
