// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg hit;
    reg [1:0] way;
    reg fill;
    wire [1:0] victim;
    reg [1:0] e_victim, m_victim;
    wire [11:0] counts;
    reg [11:0] e_counts, m_counts;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    lfu4 dut (.clk(clk), .rst(rst), .hit(hit), .way(way), .fill(fill), .victim(victim), .counts(counts));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "reset and fill";
            1: tb_gname = "frequency wins";
            2: tb_gname = "aging halves all counters";
            3: tb_gname = "fill has priority over hit";
            4: tb_gname = "2500 random hits and fills";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((victim ^ e_victim) & m_victim) !== 0) ||
                (((counts ^ e_counts) & m_counts) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h hit=%h way=%h fill=%h -> expected victim=%h counts=%h, got victim=%h counts=%h",
                             tb_vec, $time, rst, hit, way, fill, e_victim, e_counts, victim, counts);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h\n", tb_grp, rst, hit, way, fill, e_victim, m_victim, e_counts, m_counts) == 9) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 2525)
            $display("FAIL: testbench read %0d of 2525 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #26250;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
