// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    logic clk = 1'b0;
    logic rst = 1'b1;
    logic en = '0;
    logic [3:0] count = '0;
    int trace;

    chk_counter dut (.clk(clk), .rst(rst), .en(en), .count(count));

    always #5 clk = ~clk;

    initial begin
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        if (!$value$plusargs("trace=%d", trace)) trace = 0;
        case (trace)
            0: begin
                @(negedge clk); rst = 1'd1; en = 1'd0; count = 4'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0; en = 1'd1;
                @(negedge clk); count = 4'd1;
                @(negedge clk); count = 4'd2;
                @(negedge clk); count = 4'd3;
                @(negedge clk); en = 1'd0; count = 4'd4;
                @(negedge clk); en = 1'd1;
                @(negedge clk); count = 4'd5;
                @(negedge clk); en = 1'd0; count = 4'd6;
            end
            1: begin
                @(negedge clk); rst = 1'd1; en = 1'd0; count = 4'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0; en = 1'd1;
                @(negedge clk); count = 4'd1;
                @(negedge clk); count = 4'd2;
                @(negedge clk); count = 4'd4;
                @(negedge clk); count = 4'd5;
                @(negedge clk); count = 4'd6;
                @(negedge clk); count = 4'd7;
                @(negedge clk); count = 4'd8;
            end
            2: begin
                @(negedge clk); rst = 1'd1; en = 1'd0; count = 4'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0; en = 1'd1;
                @(negedge clk); count = 4'd1;
                @(negedge clk); en = 1'd0; count = 4'd2;
                @(negedge clk); count = 4'd3;
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
            end
            3: begin
                @(negedge clk); rst = 1'd1; en = 1'd0; count = 4'd7;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
            end
            4: begin
                @(negedge clk); rst = 1'd1; en = 1'd0; count = 4'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0; en = 1'd1;
                @(negedge clk); count = 4'd1;
                @(negedge clk); count = 4'd2;
                @(negedge clk); count = 4'd3;
                @(negedge clk); count = 4'd4;
                @(negedge clk); count = 4'd5;
                @(negedge clk); count = 4'd6;
                @(negedge clk); count = 4'd7;
                @(negedge clk); count = 4'd8;
                @(negedge clk); count = 4'd9;
                @(negedge clk); count = 4'd10;
                @(negedge clk); count = 4'd11;
                @(negedge clk); count = 4'd12;
                @(negedge clk); count = 4'd13;
                @(negedge clk); count = 4'd14;
                @(negedge clk); count = 4'd15;
                @(negedge clk); count = 4'd0;
                @(negedge clk); count = 4'd1;
                @(negedge clk); count = 4'd2;
                @(negedge clk); en = 1'd0; count = 4'd3;
            end
            default: ;
        endcase
        repeat (3) @(negedge clk);
        $display("TRACE_DONE");
        $finish;
    end
endmodule
