-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal clk : std_logic := '0';
    signal track : std_logic := '0';
    signal vin : real := 0.0;
    signal vout : real;
    signal tb_done : boolean := false;
begin
    dut : entity work.sample_hold generic map (DROOP => 0.98)
        port map (clk => clk, track => track, vin => vin, vout => vout);

    clk <= not clk after 5 ns when not tb_done;

    watchdog : process
    begin
        wait for 16680 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_track : std_logic_vector(0 downto 0);
        variable v_vin : real;
        variable e_vout : real;
        variable m_vout : std_logic_vector(3 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "track mode follows vin";
                when 1 => return "hold with droop";
                when 2 => return "re-acquire after holding";
                when 3 => return "1500 cycles: sine input, random track/hold";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait until falling_edge(clk);
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_track);
            read(tb_l, v_vin);
            read(tb_l, e_vout);
            hread(tb_l, m_vout);
            track <= v_track(0);
            vin <= v_vin;
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait until falling_edge(clk);
            tb_bad := (m_vout(0) = '1' and not (abs(vout - e_vout) <= 1.000000e-09));
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "track=" & to_hstring(v_track) & " " & "vin=" & real'image(v_vin) &
                        " -> expected " & "vout=" & real'image(e_vout) &
                        ", got " & "vout=" & real'image(vout));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 1568 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 1568 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
