// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg rd_en;
    reg [3:0] wr_gray_sync;
    wire [3:0] rd_gray;
    reg [3:0] e_rd_gray, m_rd_gray;
    wire [2:0] rd_addr;
    reg [2:0] e_rd_addr, m_rd_addr;
    wire empty;
    reg e_empty, m_empty;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    rd_ptr_gray dut (.clk(clk), .rst(rst), .rd_en(rd_en), .wr_gray_sync(wr_gray_sync), .rd_gray(rd_gray), .rd_addr(rd_addr), .empty(empty));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "empty until data arrives";
            1: tb_gname = "pops follow the write pointer";
            2: tb_gname = "wrap-around of the 4-bit pointer";
            3: tb_gname = "2000 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((rd_gray ^ e_rd_gray) & m_rd_gray) !== 0) ||
                (((rd_addr ^ e_rd_addr) & m_rd_addr) !== 0) ||
                (((empty ^ e_empty) & m_empty) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h rd_en=%h wr_gray_sync=%h -> expected rd_gray=%h rd_addr=%h empty=%h, got rd_gray=%h rd_addr=%h empty=%h",
                             tb_vec, $time, rst, rd_en, wr_gray_sync, e_rd_gray, e_rd_addr, e_empty, rd_gray, rd_addr, empty);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, rd_en, wr_gray_sync, e_rd_gray, m_rd_gray, e_rd_addr, m_rd_addr, e_empty, m_empty) == 10) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 2047)
            $display("FAIL: testbench read %0d of 2047 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #21470;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
