-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal clk : std_logic := '0';
    signal rst : std_logic := '0';
    signal rd_en : std_logic := '0';
    signal wr_gray_sync : std_logic_vector(3 downto 0) := (others => '0');
    signal rd_gray : std_logic_vector(3 downto 0);
    signal rd_addr : std_logic_vector(2 downto 0);
    signal empty : std_logic;
    signal tb_done : boolean := false;
begin
    dut : entity work.rd_ptr_gray
        port map (clk => clk, rst => rst, rd_en => rd_en, wr_gray_sync => wr_gray_sync, rd_gray => rd_gray, rd_addr => rd_addr, empty => empty);

    clk <= not clk after 5 ns when not tb_done;

    watchdog : process
    begin
        wait for 21470 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_rst : std_logic_vector(0 downto 0);
        variable v_rd_en : std_logic_vector(0 downto 0);
        variable v_wr_gray_sync : std_logic_vector(3 downto 0);
        variable e_rd_gray, m_rd_gray : std_logic_vector(3 downto 0);
        variable e_rd_addr, m_rd_addr : std_logic_vector(2 downto 0);
        variable e_empty, m_empty : std_logic_vector(0 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "empty until data arrives";
                when 1 => return "pops follow the write pointer";
                when 2 => return "wrap-around of the 4-bit pointer";
                when 3 => return "2000 random cycles";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait until falling_edge(clk);
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_rst);
            hread(tb_l, v_rd_en);
            hread(tb_l, v_wr_gray_sync);
            hread(tb_l, e_rd_gray);
            hread(tb_l, m_rd_gray);
            hread(tb_l, e_rd_addr);
            hread(tb_l, m_rd_addr);
            hread(tb_l, e_empty);
            hread(tb_l, m_empty);
            rst <= v_rst(0);
            rd_en <= v_rd_en(0);
            wr_gray_sync <= v_wr_gray_sync;
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait until falling_edge(clk);
            tb_bad := tb_diff(sv(rd_gray), e_rd_gray, m_rd_gray)
                   or tb_diff(sv(rd_addr), e_rd_addr, m_rd_addr)
                   or tb_diff(sv(empty), e_empty, m_empty);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "rst=" & to_hstring(v_rst) & " " & "rd_en=" & to_hstring(v_rd_en) & " " & "wr_gray_sync=" & to_hstring(v_wr_gray_sync) &
                        " -> expected " & "rd_gray=" & to_hstring(e_rd_gray) & " " & "rd_addr=" & to_hstring(e_rd_addr) & " " & "empty=" & to_hstring(e_empty) &
                        ", got " & "rd_gray=" & to_hstring(sv(rd_gray)) & " " & "rd_addr=" & to_hstring(sv(rd_addr)) & " " & "empty=" & to_hstring(sv(empty)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 2047 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 2047 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
