// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg [15:0] a;
    reg [15:0] b;
    reg [3:0] op;
    wire [15:0] y;
    reg [15:0] e_y, m_y;
    wire zero;
    reg e_zero, m_zero;
    wire carry;
    reg e_carry, m_carry;
    wire overflow;
    reg e_overflow, m_overflow;
    wire negative;
    reg e_negative, m_negative;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    alu #(.WIDTH(16)) dut (.a(a), .b(b), .op(op), .y(y), .zero(zero), .carry(carry), .overflow(overflow), .negative(negative));

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "ADD";
            1: tb_gname = "SUB";
            2: tb_gname = "AND";
            3: tb_gname = "OR";
            4: tb_gname = "XOR";
            5: tb_gname = "NOR";
            6: tb_gname = "SLL";
            7: tb_gname = "SRL";
            8: tb_gname = "SRA";
            9: tb_gname = "SLT";
            10: tb_gname = "SLTU";
            11: tb_gname = "unused opcodes give 0";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((y ^ e_y) & m_y) !== 0) ||
                (((zero ^ e_zero) & m_zero) !== 0) ||
                (((carry ^ e_carry) & m_carry) !== 0) ||
                (((overflow ^ e_overflow) & m_overflow) !== 0) ||
                (((negative ^ e_negative) & m_negative) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): a=%h b=%h op=%h -> expected y=%h zero=%h carry=%h overflow=%h negative=%h, got y=%h zero=%h carry=%h overflow=%h negative=%h",
                             tb_vec, $time, a, b, op, e_y, e_zero, e_carry, e_overflow, e_negative, y, zero, carry, overflow, negative);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        #1;
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, a, b, op, e_y, m_y, e_zero, m_zero, e_carry, m_carry, e_overflow, m_overflow, e_negative, m_negative) == 14) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            #5;
            tb_check;
            #5;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3586)
            $display("FAIL: testbench read %0d of 3586 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #36860;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
