-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal a : std_logic_vector(15 downto 0) := (others => '0');
    signal b : std_logic_vector(15 downto 0) := (others => '0');
    signal op : std_logic_vector(3 downto 0) := (others => '0');
    signal y : std_logic_vector(15 downto 0);
    signal zero : std_logic;
    signal carry : std_logic;
    signal overflow : std_logic;
    signal negative : std_logic;
    signal tb_done : boolean := false;
begin
    dut : entity work.alu generic map (WIDTH => 16)
        port map (a => a, b => b, op => op, y => y, zero => zero, carry => carry, overflow => overflow, negative => negative);

    watchdog : process
    begin
        wait for 36860 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_a : std_logic_vector(15 downto 0);
        variable v_b : std_logic_vector(15 downto 0);
        variable v_op : std_logic_vector(3 downto 0);
        variable e_y, m_y : std_logic_vector(15 downto 0);
        variable e_zero, m_zero : std_logic_vector(0 downto 0);
        variable e_carry, m_carry : std_logic_vector(0 downto 0);
        variable e_overflow, m_overflow : std_logic_vector(0 downto 0);
        variable e_negative, m_negative : std_logic_vector(0 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "ADD";
                when 1 => return "SUB";
                when 2 => return "AND";
                when 3 => return "OR";
                when 4 => return "XOR";
                when 5 => return "NOR";
                when 6 => return "SLL";
                when 7 => return "SRL";
                when 8 => return "SRA";
                when 9 => return "SLT";
                when 10 => return "SLTU";
                when 11 => return "unused opcodes give 0";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait for 1 ns;
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_a);
            hread(tb_l, v_b);
            hread(tb_l, v_op);
            hread(tb_l, e_y);
            hread(tb_l, m_y);
            hread(tb_l, e_zero);
            hread(tb_l, m_zero);
            hread(tb_l, e_carry);
            hread(tb_l, m_carry);
            hread(tb_l, e_overflow);
            hread(tb_l, m_overflow);
            hread(tb_l, e_negative);
            hread(tb_l, m_negative);
            a <= v_a;
            b <= v_b;
            op <= v_op;
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait for 5 ns;
            tb_bad := tb_diff(sv(y), e_y, m_y)
                   or tb_diff(sv(zero), e_zero, m_zero)
                   or tb_diff(sv(carry), e_carry, m_carry)
                   or tb_diff(sv(overflow), e_overflow, m_overflow)
                   or tb_diff(sv(negative), e_negative, m_negative);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "a=" & to_hstring(v_a) & " " & "b=" & to_hstring(v_b) & " " & "op=" & to_hstring(v_op) &
                        " -> expected " & "y=" & to_hstring(e_y) & " " & "zero=" & to_hstring(e_zero) & " " & "carry=" & to_hstring(e_carry) & " " & "overflow=" & to_hstring(e_overflow) & " " & "negative=" & to_hstring(e_negative) &
                        ", got " & "y=" & to_hstring(sv(y)) & " " & "zero=" & to_hstring(sv(zero)) & " " & "carry=" & to_hstring(sv(carry)) & " " & "overflow=" & to_hstring(sv(overflow)) & " " & "negative=" & to_hstring(sv(negative)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
            wait for 5 ns;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 3586 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 3586 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
