// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg valid;
    reg [7:0] din;
    wire [7:0] bus_q;
    reg [7:0] e_bus_q, m_bus_q;
    wire inv;
    reg e_inv, m_inv;
    wire [7:0] dout;
    reg [7:0] e_dout, m_dout;
    wire [15:0] toggles;
    reg [15:0] e_toggles, m_toggles;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    bus_invert dut (.clk(clk), .rst(rst), .valid(valid), .din(din), .bus_q(bus_q), .inv(inv), .dout(dout), .toggles(toggles));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "inverts when more than half the bits flip";
            1: tb_gname = "no inversion at exactly 4";
            2: tb_gname = "holds without valid";
            3: tb_gname = "decoder recovers data (3000 random words)";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((bus_q ^ e_bus_q) & m_bus_q) !== 0) ||
                (((inv ^ e_inv) & m_inv) !== 0) ||
                (((dout ^ e_dout) & m_dout) !== 0) ||
                (((toggles ^ e_toggles) & m_toggles) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h valid=%h din=%h -> expected bus_q=%h inv=%h dout=%h toggles=%h, got bus_q=%h inv=%h dout=%h toggles=%h",
                             tb_vec, $time, rst, valid, din, e_bus_q, e_inv, e_dout, e_toggles, bus_q, inv, dout, toggles);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, valid, din, e_bus_q, m_bus_q, e_inv, m_inv, e_dout, m_dout, e_toggles, m_toggles) == 12) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3009)
            $display("FAIL: testbench read %0d of 3009 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #31090;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
