-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal clk : std_logic := '0';
    signal rst : std_logic := '0';
    signal valid : std_logic := '0';
    signal din : std_logic_vector(7 downto 0) := (others => '0');
    signal bus_q : std_logic_vector(7 downto 0);
    signal inv : std_logic;
    signal dout : std_logic_vector(7 downto 0);
    signal toggles : std_logic_vector(15 downto 0);
    signal tb_done : boolean := false;
begin
    dut : entity work.bus_invert
        port map (clk => clk, rst => rst, valid => valid, din => din, bus_q => bus_q, inv => inv, dout => dout, toggles => toggles);

    clk <= not clk after 5 ns when not tb_done;

    watchdog : process
    begin
        wait for 31090 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_rst : std_logic_vector(0 downto 0);
        variable v_valid : std_logic_vector(0 downto 0);
        variable v_din : std_logic_vector(7 downto 0);
        variable e_bus_q, m_bus_q : std_logic_vector(7 downto 0);
        variable e_inv, m_inv : std_logic_vector(0 downto 0);
        variable e_dout, m_dout : std_logic_vector(7 downto 0);
        variable e_toggles, m_toggles : std_logic_vector(15 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "inverts when more than half the bits flip";
                when 1 => return "no inversion at exactly 4";
                when 2 => return "holds without valid";
                when 3 => return "decoder recovers data (3000 random words)";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait until falling_edge(clk);
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_rst);
            hread(tb_l, v_valid);
            hread(tb_l, v_din);
            hread(tb_l, e_bus_q);
            hread(tb_l, m_bus_q);
            hread(tb_l, e_inv);
            hread(tb_l, m_inv);
            hread(tb_l, e_dout);
            hread(tb_l, m_dout);
            hread(tb_l, e_toggles);
            hread(tb_l, m_toggles);
            rst <= v_rst(0);
            valid <= v_valid(0);
            din <= v_din;
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait until falling_edge(clk);
            tb_bad := tb_diff(sv(bus_q), e_bus_q, m_bus_q)
                   or tb_diff(sv(inv), e_inv, m_inv)
                   or tb_diff(sv(dout), e_dout, m_dout)
                   or tb_diff(sv(toggles), e_toggles, m_toggles);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "rst=" & to_hstring(v_rst) & " " & "valid=" & to_hstring(v_valid) & " " & "din=" & to_hstring(v_din) &
                        " -> expected " & "bus_q=" & to_hstring(e_bus_q) & " " & "inv=" & to_hstring(e_inv) & " " & "dout=" & to_hstring(e_dout) & " " & "toggles=" & to_hstring(e_toggles) &
                        ", got " & "bus_q=" & to_hstring(sv(bus_q)) & " " & "inv=" & to_hstring(sv(inv)) & " " & "dout=" & to_hstring(sv(dout)) & " " & "toggles=" & to_hstring(sv(toggles)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 3009 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 3009 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
