// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg en;
    reg se;
    reg si;
    wire [3:0] count;
    reg [3:0] e_count, m_count;
    wire tc;
    reg e_tc, m_tc;
    wire so;
    reg e_so, m_so;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    scan_counter dut (.clk(clk), .rst(rst), .en(en), .se(se), .si(si), .count(count), .tc(tc), .so(so));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "functional counting";
            1: tb_gname = "scan load, capture, unload";
            2: tb_gname = "scan mode ignores enable";
            3: tb_gname = "1500 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((count ^ e_count) & m_count) !== 0) ||
                (((tc ^ e_tc) & m_tc) !== 0) ||
                (((so ^ e_so) & m_so) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h en=%h se=%h si=%h -> expected count=%h tc=%h so=%h, got count=%h tc=%h so=%h",
                             tb_vec, $time, rst, en, se, si, e_count, e_tc, e_so, count, tc, so);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, en, se, si, e_count, m_count, e_tc, m_tc, e_so, m_so) == 11) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 1532)
            $display("FAIL: testbench read %0d of 1532 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #16320;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
