// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg in_valid;
    reg [7:0] in_data;
    reg credit_ret;
    wire in_ready;
    reg e_in_ready, m_in_ready;
    wire tx_valid;
    reg e_tx_valid, m_tx_valid;
    wire [7:0] tx_data;
    reg [7:0] e_tx_data, m_tx_data;
    wire [2:0] credits;
    reg [2:0] e_credits, m_credits;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    credit_tx dut (.clk(clk), .rst(rst), .in_valid(in_valid), .in_data(in_data), .credit_ret(credit_ret), .in_ready(in_ready), .tx_valid(tx_valid), .tx_data(tx_data), .credits(credits));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "stops at zero credits";
            1: tb_gname = "simultaneous send and return";
            2: tb_gname = "3000 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((in_ready ^ e_in_ready) & m_in_ready) !== 0) ||
                (((tx_valid ^ e_tx_valid) & m_tx_valid) !== 0) ||
                (((tx_data ^ e_tx_data) & m_tx_data) !== 0) ||
                (((credits ^ e_credits) & m_credits) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h in_valid=%h in_data=%h credit_ret=%h -> expected in_ready=%h tx_valid=%h tx_data=%h credits=%h, got in_ready=%h tx_valid=%h tx_data=%h credits=%h",
                             tb_vec, $time, rst, in_valid, in_data, credit_ret, e_in_ready, e_tx_valid, e_tx_data, e_credits, in_ready, tx_valid, tx_data, credits);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, in_valid, in_data, credit_ret, e_in_ready, m_in_ready, e_tx_valid, m_tx_valid, e_tx_data, m_tx_data, e_credits, m_credits) == 13) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3010)
            $display("FAIL: testbench read %0d of 3010 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #31100;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
