// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg [7:0] a;
    reg [7:0] b;
    wire [7:0] sum;
    reg [7:0] e_sum, m_sum;
    wire ovf;
    reg e_ovf, m_ovf;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    sat_add8 dut (.a(a), .b(b), .sum(sum), .ovf(ovf));

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "no overflow";
            1: tb_gname = "positive overflow";
            2: tb_gname = "negative overflow";
            3: tb_gname = "boundary operands (64 pairs)";
            4: tb_gname = "4000 random pairs";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((sum ^ e_sum) & m_sum) !== 0) ||
                (((ovf ^ e_ovf) & m_ovf) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): a=%h b=%h -> expected sum=%h ovf=%h, got sum=%h ovf=%h",
                             tb_vec, $time, a, b, e_sum, e_ovf, sum, ovf);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        #1;
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h\n", tb_grp, a, b, e_sum, m_sum, e_ovf, m_ovf) == 7) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            #5;
            tb_check;
            #5;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 4077)
            $display("FAIL: testbench read %0d of 4077 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #41770;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
