// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg issue_valid;
    reg [2:0] rd;
    reg [2:0] rs1;
    reg [2:0] rs2;
    reg wb_valid;
    reg [2:0] wb_rd;
    wire issued;
    reg e_issued, m_issued;
    wire [7:0] pending;
    reg [7:0] e_pending, m_pending;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    scoreboard dut (.clk(clk), .rst(rst), .issue_valid(issue_valid), .rd(rd), .rs1(rs1), .rs2(rs2), .wb_valid(wb_valid), .wb_rd(wb_rd), .issued(issued), .pending(pending));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "reset";
            1: tb_gname = "RAW stall";
            2: tb_gname = "writeback bypass wakes the instruction";
            3: tb_gname = "WAW stall";
            4: tb_gname = "register 0 is never pending";
            5: tb_gname = "3000 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((issued ^ e_issued) & m_issued) !== 0) ||
                (((pending ^ e_pending) & m_pending) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h issue_valid=%h rd=%h rs1=%h rs2=%h wb_valid=%h wb_rd=%h -> expected issued=%h pending=%h, got issued=%h pending=%h",
                             tb_vec, $time, rst, issue_valid, rd, rs1, rs2, wb_valid, wb_rd, e_issued, e_pending, issued, pending);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, issue_valid, rd, rs1, rs2, wb_valid, wb_rd, e_issued, m_issued, e_pending, m_pending) == 12) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3010)
            $display("FAIL: testbench read %0d of 3010 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #31100;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
