-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal pclk : std_logic := '0';
    signal presetn : std_logic := '0';
    signal psel : std_logic := '0';
    signal penable : std_logic := '0';
    signal pwrite : std_logic := '0';
    signal paddr : std_logic_vector(7 downto 0) := (others => '0');
    signal pwdata : std_logic_vector(31 downto 0) := (others => '0');
    signal pstrb : std_logic_vector(3 downto 0) := (others => '0');
    signal prdata : std_logic_vector(31 downto 0);
    signal pready : std_logic;
    signal pslverr : std_logic;
    signal tb_done : boolean := false;
begin
    dut : entity work.apb_slave
        port map (pclk => pclk, presetn => presetn, psel => psel, penable => penable, pwrite => pwrite, paddr => paddr, pwdata => pwdata, pstrb => pstrb, prdata => prdata, pready => pready, pslverr => pslverr);

    pclk <= not pclk after 5 ns when not tb_done;

    watchdog : process
    begin
        wait for 27720 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_presetn : std_logic_vector(0 downto 0);
        variable v_psel : std_logic_vector(0 downto 0);
        variable v_penable : std_logic_vector(0 downto 0);
        variable v_pwrite : std_logic_vector(0 downto 0);
        variable v_paddr : std_logic_vector(7 downto 0);
        variable v_pwdata : std_logic_vector(31 downto 0);
        variable v_pstrb : std_logic_vector(3 downto 0);
        variable e_prdata, m_prdata : std_logic_vector(31 downto 0);
        variable e_pready, m_pready : std_logic_vector(0 downto 0);
        variable e_pslverr, m_pslverr : std_logic_vector(0 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "write and read back";
                when 1 => return "read-only ID and write counter";
                when 2 => return "idle bus";
                when 3 => return "byte strobes";
                when 4 => return "error responses";
                when 5 => return "1200 random transfers";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait until falling_edge(pclk);
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_presetn);
            hread(tb_l, v_psel);
            hread(tb_l, v_penable);
            hread(tb_l, v_pwrite);
            hread(tb_l, v_paddr);
            hread(tb_l, v_pwdata);
            hread(tb_l, v_pstrb);
            hread(tb_l, e_prdata);
            hread(tb_l, m_prdata);
            hread(tb_l, e_pready);
            hread(tb_l, m_pready);
            hread(tb_l, e_pslverr);
            hread(tb_l, m_pslverr);
            presetn <= v_presetn(0);
            psel <= v_psel(0);
            penable <= v_penable(0);
            pwrite <= v_pwrite(0);
            paddr <= v_paddr;
            pwdata <= v_pwdata;
            pstrb <= v_pstrb;
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait until falling_edge(pclk);
            tb_bad := tb_diff(sv(prdata), e_prdata, m_prdata)
                   or tb_diff(sv(pready), e_pready, m_pready)
                   or tb_diff(sv(pslverr), e_pslverr, m_pslverr);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "presetn=" & to_hstring(v_presetn) & " " & "psel=" & to_hstring(v_psel) & " " & "penable=" & to_hstring(v_penable) & " " & "pwrite=" & to_hstring(v_pwrite) & " " & "paddr=" & to_hstring(v_paddr) & " " & "pwdata=" & to_hstring(v_pwdata) & " " & "pstrb=" & to_hstring(v_pstrb) &
                        " -> expected " & "prdata=" & to_hstring(e_prdata) & " " & "pready=" & to_hstring(e_pready) & " " & "pslverr=" & to_hstring(e_pslverr) &
                        ", got " & "prdata=" & to_hstring(sv(prdata)) & " " & "pready=" & to_hstring(sv(pready)) & " " & "pslverr=" & to_hstring(sv(pslverr)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 2672 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 2672 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
