-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal clk : std_logic := '0';
    signal rst : std_logic := '0';
    signal start : std_logic := '0';
    signal mem_rdata : std_logic_vector(7 downto 0) := (others => '0');
    signal mem_addr : std_logic_vector(3 downto 0);
    signal mem_we : std_logic;
    signal mem_wdata : std_logic_vector(7 downto 0);
    signal busy : std_logic;
    signal done : std_logic;
    signal fail : std_logic;
    signal tb_done : boolean := false;
begin
    dut : entity work.cb_bist
        port map (clk => clk, rst => rst, start => start, mem_rdata => mem_rdata, mem_addr => mem_addr, mem_we => mem_we, mem_wdata => mem_wdata, busy => busy, done => done, fail => fail);

    clk <= not clk after 5 ns when not tb_done;

    watchdog : process
    begin
        wait for 6350 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_rst : std_logic_vector(0 downto 0);
        variable v_start : std_logic_vector(0 downto 0);
        variable v_mem_rdata : std_logic_vector(7 downto 0);
        variable e_mem_addr, m_mem_addr : std_logic_vector(3 downto 0);
        variable e_mem_we, m_mem_we : std_logic_vector(0 downto 0);
        variable e_mem_wdata, m_mem_wdata : std_logic_vector(7 downto 0);
        variable e_busy, m_busy : std_logic_vector(0 downto 0);
        variable e_done, m_done : std_logic_vector(0 downto 0);
        variable e_fail, m_fail : std_logic_vector(0 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "fault-free memory";
                when 1 => return "stuck-at fault detected";
                when 2 => return "restart and reset";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait until falling_edge(clk);
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_rst);
            hread(tb_l, v_start);
            hread(tb_l, v_mem_rdata);
            hread(tb_l, e_mem_addr);
            hread(tb_l, m_mem_addr);
            hread(tb_l, e_mem_we);
            hread(tb_l, m_mem_we);
            hread(tb_l, e_mem_wdata);
            hread(tb_l, m_mem_wdata);
            hread(tb_l, e_busy);
            hread(tb_l, m_busy);
            hread(tb_l, e_done);
            hread(tb_l, m_done);
            hread(tb_l, e_fail);
            hread(tb_l, m_fail);
            rst <= v_rst(0);
            start <= v_start(0);
            mem_rdata <= v_mem_rdata;
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait until falling_edge(clk);
            tb_bad := tb_diff(sv(mem_addr), e_mem_addr, m_mem_addr)
                   or tb_diff(sv(mem_we), e_mem_we, m_mem_we)
                   or tb_diff(sv(mem_wdata), e_mem_wdata, m_mem_wdata)
                   or tb_diff(sv(busy), e_busy, m_busy)
                   or tb_diff(sv(done), e_done, m_done)
                   or tb_diff(sv(fail), e_fail, m_fail);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "rst=" & to_hstring(v_rst) & " " & "start=" & to_hstring(v_start) & " " & "mem_rdata=" & to_hstring(v_mem_rdata) &
                        " -> expected " & "mem_addr=" & to_hstring(e_mem_addr) & " " & "mem_we=" & to_hstring(e_mem_we) & " " & "mem_wdata=" & to_hstring(e_mem_wdata) & " " & "busy=" & to_hstring(e_busy) & " " & "done=" & to_hstring(e_done) & " " & "fail=" & to_hstring(e_fail) &
                        ", got " & "mem_addr=" & to_hstring(sv(mem_addr)) & " " & "mem_we=" & to_hstring(sv(mem_we)) & " " & "mem_wdata=" & to_hstring(sv(mem_wdata)) & " " & "busy=" & to_hstring(sv(busy)) & " " & "done=" & to_hstring(sv(done)) & " " & "fail=" & to_hstring(sv(fail)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 535 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 535 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
