// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg [3:0] a;
    reg [3:0] b;
    reg cin;
    wire [3:0] sum;
    reg [3:0] e_sum, m_sum;
    wire cout;
    reg e_cout, m_cout;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    bcd_add dut (.a(a), .b(b), .cin(cin), .sum(sum), .cout(cout));

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "all digit pairs";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((sum ^ e_sum) & m_sum) !== 0) ||
                (((cout ^ e_cout) & m_cout) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): a=%h b=%h cin=%h -> expected sum=%h cout=%h, got sum=%h cout=%h",
                             tb_vec, $time, a, b, cin, e_sum, e_cout, sum, cout);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        #1;
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h\n", tb_grp, a, b, cin, e_sum, m_sum, e_cout, m_cout) == 8) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            #5;
            tb_check;
            #5;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 200)
            $display("FAIL: testbench read %0d of 200 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #3000;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
