// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg load;
    reg [7:0] din;
    reg shift;
    reg dir;
    reg serial_in;
    wire [7:0] q;
    reg [7:0] e_q, m_q;
    wire serial_out;
    reg e_serial_out, m_serial_out;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    shift_reg dut (.clk(clk), .rst(rst), .load(load), .din(din), .shift(shift), .dir(dir), .serial_in(serial_in), .q(q), .serial_out(serial_out));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "parallel load";
            1: tb_gname = "shift left";
            2: tb_gname = "shift right";
            3: tb_gname = "load has priority over shift";
            4: tb_gname = "hold";
            5: tb_gname = "1500 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((q ^ e_q) & m_q) !== 0) ||
                (((serial_out ^ e_serial_out) & m_serial_out) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h load=%h din=%h shift=%h dir=%h serial_in=%h -> expected q=%h serial_out=%h, got q=%h serial_out=%h",
                             tb_vec, $time, rst, load, din, shift, dir, serial_in, e_q, e_serial_out, q, serial_out);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, load, din, shift, dir, serial_in, e_q, m_q, e_serial_out, m_serial_out) == 11) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 1525)
            $display("FAIL: testbench read %0d of 1525 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #16250;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
