// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg capture_dr;
    reg shift_dr;
    reg update_dr;
    reg mode;
    reg scan_in;
    reg [3:0] data_in;
    wire [3:0] data_out;
    reg [3:0] e_data_out, m_data_out;
    wire scan_out;
    reg e_scan_out, m_scan_out;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    bsr4 dut (.clk(clk), .rst(rst), .capture_dr(capture_dr), .shift_dr(shift_dr), .update_dr(update_dr), .mode(mode), .scan_in(scan_in), .data_in(data_in), .data_out(data_out), .scan_out(scan_out));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "capture pins and shift out";
            1: tb_gname = "shift in, update, drive pins";
            2: tb_gname = "normal mode passes pins through";
            3: tb_gname = "3000 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((data_out ^ e_data_out) & m_data_out) !== 0) ||
                (((scan_out ^ e_scan_out) & m_scan_out) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h capture_dr=%h shift_dr=%h update_dr=%h mode=%h scan_in=%h data_in=%h -> expected data_out=%h scan_out=%h, got data_out=%h scan_out=%h",
                             tb_vec, $time, rst, capture_dr, shift_dr, update_dr, mode, scan_in, data_in, e_data_out, e_scan_out, data_out, scan_out);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, capture_dr, shift_dr, update_dr, mode, scan_in, data_in, e_data_out, m_data_out, e_scan_out, m_scan_out) == 12) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3013)
            $display("FAIL: testbench read %0d of 3013 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #31130;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
