-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal iso_en : std_logic := '0';
    signal pd_data : std_logic_vector(7 downto 0) := (others => '0');
    signal pd_valid : std_logic := '0';
    signal pd_req_n : std_logic := '0';
    signal ao_data : std_logic_vector(7 downto 0);
    signal ao_valid : std_logic;
    signal ao_req_n : std_logic;
    signal tb_done : boolean := false;
begin
    dut : entity work.iso_cells
        port map (iso_en => iso_en, pd_data => pd_data, pd_valid => pd_valid, pd_req_n => pd_req_n, ao_data => ao_data, ao_valid => ao_valid, ao_req_n => ao_req_n);

    watchdog : process
    begin
        wait for 6080 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_iso_en : std_logic_vector(0 downto 0);
        variable v_pd_data : std_logic_vector(7 downto 0);
        variable v_pd_valid : std_logic_vector(0 downto 0);
        variable v_pd_req_n : std_logic_vector(0 downto 0);
        variable e_ao_data, m_ao_data : std_logic_vector(7 downto 0);
        variable e_ao_valid, m_ao_valid : std_logic_vector(0 downto 0);
        variable e_ao_req_n, m_ao_req_n : std_logic_vector(0 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "pass-through when not isolated";
                when 1 => return "clamped to inactive values";
                when 2 => return "500 random";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait for 1 ns;
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_iso_en);
            hread(tb_l, v_pd_data);
            hread(tb_l, v_pd_valid);
            hread(tb_l, v_pd_req_n);
            hread(tb_l, e_ao_data);
            hread(tb_l, m_ao_data);
            hread(tb_l, e_ao_valid);
            hread(tb_l, m_ao_valid);
            hread(tb_l, e_ao_req_n);
            hread(tb_l, m_ao_req_n);
            iso_en <= v_iso_en(0);
            pd_data <= v_pd_data;
            pd_valid <= v_pd_valid(0);
            pd_req_n <= v_pd_req_n(0);
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait for 5 ns;
            tb_bad := tb_diff(sv(ao_data), e_ao_data, m_ao_data)
                   or tb_diff(sv(ao_valid), e_ao_valid, m_ao_valid)
                   or tb_diff(sv(ao_req_n), e_ao_req_n, m_ao_req_n);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "iso_en=" & to_hstring(v_iso_en) & " " & "pd_data=" & to_hstring(v_pd_data) & " " & "pd_valid=" & to_hstring(v_pd_valid) & " " & "pd_req_n=" & to_hstring(v_pd_req_n) &
                        " -> expected " & "ao_data=" & to_hstring(e_ao_data) & " " & "ao_valid=" & to_hstring(e_ao_valid) & " " & "ao_req_n=" & to_hstring(e_ao_req_n) &
                        ", got " & "ao_data=" & to_hstring(sv(ao_data)) & " " & "ao_valid=" & to_hstring(sv(ao_valid)) & " " & "ao_req_n=" & to_hstring(sv(ao_req_n)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
            wait for 5 ns;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 508 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 508 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
