// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    logic clk = 1'b0;
    logic rst = 1'b1;
    logic [3:0] req = '0;
    logic [3:0] gnt = '0;
    int trace;

    chk_starve dut (.clk(clk), .rst(rst), .req(req), .gnt(gnt));

    always #5 clk = ~clk;

    initial begin
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        if (!$value$plusargs("trace=%d", trace)) trace = 0;
        case (trace)
            0: begin
                @(negedge clk); rst = 1'd1; req = 4'd0; gnt = 4'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); req = 4'd15; gnt = 4'd1;
                @(negedge clk); req = 4'd14; gnt = 4'd2;
                @(negedge clk); req = 4'd12; gnt = 4'd4;
                @(negedge clk); req = 4'd8; gnt = 4'd8;
                @(negedge clk); req = 4'd0; gnt = 4'd0;
                @(negedge clk); 
            end
            1: begin
                @(negedge clk); rst = 1'd1; req = 4'd0; gnt = 4'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); req = 4'd4; gnt = 4'd4;
                @(negedge clk); req = 4'd0; gnt = 4'd0;
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
            end
            2: begin
                @(negedge clk); rst = 1'd1; req = 4'd0; gnt = 4'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); req = 4'd9; gnt = 4'd1;
                @(negedge clk); req = 4'd8; gnt = 4'd0;
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); gnt = 4'd8;
                @(negedge clk); req = 4'd0; gnt = 4'd0;
            end
            3: begin
                @(negedge clk); rst = 1'd1; req = 4'd0; gnt = 4'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); req = 4'd2;
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
            end
            default: ;
        endcase
        repeat (3) @(negedge clk);
        $display("TRACE_DONE");
        $finish;
    end
endmodule
