"""Authoring tool: build vector-driven hidden testbenches from a Python reference model.

A problem that has problems/<slug>/gen.py can be (re)generated with

    python3 -m hwlc gen <slug>

which writes tb/vectors.txt, tb/tb.sv, tb/tb.vhd (and starter files that do not exist yet).

gen.py defines:

    CLOCK = "clk"            # name of the clock port, or None for combinational designs
    PARAMS = {}              # optional parameter / generic overrides for the DUT instance
    TOL = {"vout": 1e-9}     # absolute tolerance for real-valued outputs (default 1e-9)

    def vectors():
        # yield (check_name, {input: value}, {output: expected})
        ...

Every yielded tuple is one vector. Vectors of the same check must be consecutive; each check
becomes one PASS/FAIL line. An expected value of None means "don't care"; (value, mask) checks
only the bits set in mask.

Timing. Combinational: inputs are applied, outputs are checked 5 ns later, next vector 5 ns
after that. Clocked (period 10 ns): the inputs of vector i are applied at a falling edge and the
outputs are checked at the next falling edge, i.e. after the rising edge that consumed them —
so expected values are the outputs *after* that rising edge, with vector i's inputs still applied.
"""
import importlib.util
import json
import math
from pathlib import Path

from .problems import LANGUAGES

HEADER = "// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.\n"


def load_gen(problem):
    path = problem.path / "gen.py"
    spec = importlib.util.spec_from_file_location(f"hwlc_gen_{problem.slug}", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _hexw(width):
    return max(1, math.ceil(width / 4))


def _fmt_bits(value, width):
    return format(int(value) & ((1 << width) - 1), "0%dx" % _hexw(width))


def _fmt_real(value):
    return "%.17e" % float(value)


class Spec:
    def __init__(self, problem, gen):
        self.p = problem
        self.clock = getattr(gen, "CLOCK", None)
        self.params = getattr(gen, "PARAMS", {})
        self.tol = getattr(gen, "TOL", {})
        ports = [x for x in problem.ports if x["name"] != self.clock]
        self.ins = [x for x in ports if x["dir"] == "input"]
        self.outs = [x for x in ports if x["dir"] == "output"]

    @staticmethod
    def is_real(port):
        return port.get("type") == "real"


VHDL_RESERVED = set("""abs access after alias all and architecture array assert attribute begin block
body buffer bus case component configuration constant disconnect downto else elsif end entity exit file
for function generate generic group guarded if impure in inertial inout is label library linkage literal
loop map mod nand new next nor not null of on open or others out package port postponed procedure process
pure range record register reject rem report return rol ror select severity signal shared sla sll sra srl
subtype then to transport type unaffected units until use variable wait when while with xnor xor
context force parameter release default""".split())
# names the generated VHDL testbench itself declares (std.textio, helpers)
VHDL_TB_NAMES = {"line", "text", "tb", "input", "output", "read", "write", "width"}


def _build_checker(problem, gen):
    """Checker problems: gen.TRACES = [(name, violation, {signal: values})] -> tb.sv + traces.json.

    Each signal's values are a string of digits (1-bit signals, one char per cycle) or a list of
    integers. Shorter signals keep their last value. Signals are applied at falling edges, so the
    checker samples them on the following rising edge.
    """
    clock = getattr(gen, "CLOCK", "clk")
    ins = [x for x in problem.ports if x["name"] != clock]
    L = [HEADER.rstrip(), "`timescale 1ns/1ps", "module tb;", f"    logic {clock} = 1'b0;"]
    for x in ins:
        rng = f"[{x['width'] - 1}:0] " if x["width"] > 1 else ""
        init = "1'b1" if x["name"] in ("rst", "reset") else "'0"   # start in reset: checkers idle
        L.append(f"    logic {rng}{x['name']} = {init};")
    L += ["    int trace;", "",
          f"    {problem.top} dut ({', '.join(f'.{n}({n})' for n in [clock] + [x['name'] for x in ins])});", "",
          f"    always #5 {clock} = ~{clock};", "",
          "    initial begin",
          '        if ($test$plusargs("vcd")) begin',
          '            $dumpfile("wave.vcd");',
          "            $dumpvars(1, dut);",
          "        end",
          '        if (!$value$plusargs("trace=%d", trace)) trace = 0;',
          "        case (trace)"]
    traces = []
    for i, (name, violation, sigs) in enumerate(gen.TRACES):
        traces.append({"name": name, "violation": bool(violation)})
        seqs = {}
        for k, v in sigs.items():
            seqs[k] = [int(c) for c in v] if isinstance(v, str) else list(v)
        n = max(len(v) for v in seqs.values())
        L.append(f"            {i}: begin")
        for c in range(n):
            assigns = []
            for x in ins:
                seq = seqs.get(x["name"])
                if seq and c < len(seq) and (c == 0 or seq[c] != seq[c - 1]):
                    assigns.append(f"{x['name']} = {x['width']}'d{seq[c]};")
            L.append(f"                @(negedge {clock}); " + " ".join(assigns))
        L.append("            end")
    L += ["            default: ;", "        endcase",
          f"        repeat (3) @(negedge {clock});",
          '        $display("TRACE_DONE");', "        $finish;", "    end", "endmodule", ""]
    tb = problem.path / "tb"
    tb.mkdir(exist_ok=True)
    (tb / "tb.sv").write_text("\n".join(L))
    (tb / "traces.json").write_text(json.dumps(traces, indent=1) + "\n")
    for ex in problem.examples:
        if not any(t["name"].startswith(ex["check"]) for t in traces):
            raise ValueError(f"example check '{ex['check']}' matches no trace name")
    written = []
    f = problem.path / "starter" / "systemverilog.sv"
    if not f.exists():
        f.parent.mkdir(exist_ok=True)
        decl = ",\n".join(f"    input logic {('[%d:0] ' % (x['width'] - 1)) if x['width'] > 1 else ''}{x['name']}"
                          for x in problem.ports)
        f.write_text(f"module {problem.top} (\n{decl}\n);\n\n    // Your assertions here\n\nendmodule\n")
        written.append(f.name)
    from . import waves
    waves.build(problem, gen)
    return len(traces), [t["name"] for t in traces], written


def build(problem):
    gen = load_gen(problem)
    if hasattr(gen, "TRACES"):
        return _build_checker(problem, gen)
    if "vhdl" in problem.languages:
        bad = [x["name"] for x in problem.ports if x["name"].lower() in VHDL_RESERVED]
        if bad:
            raise ValueError(f"port name(s) {bad} are VHDL reserved words")
        clash = [x["name"] for x in problem.ports if x["name"].lower() in VHDL_TB_NAMES]
        if clash:
            raise ValueError(f"port name(s) {clash} clash with names used by the VHDL testbench")
    spec = Spec(problem, gen)
    groups, lines = [], []
    last = None
    for name, ins, outs in gen.vectors():
        if name != last:
            if name in groups:
                raise ValueError(f"check '{name}' is not contiguous")
            groups.append(name)
            last = name
        gid = len(groups) - 1
        fields = [str(gid)]
        for port in spec.ins:
            v = ins.get(port["name"], 0)
            fields.append(_fmt_real(v) if spec.is_real(port) else _fmt_bits(v, port["width"]))
        for port in spec.outs:
            exp = outs.get(port["name"])
            if spec.is_real(port):
                fields += [_fmt_real(0.0 if exp is None else exp), "0" if exp is None else "1"]
            else:
                w = port["width"]
                if exp is None:
                    val, mask = 0, 0
                elif isinstance(exp, tuple):
                    val, mask = exp
                else:
                    val, mask = exp, (1 << w) - 1
                fields += [_fmt_bits(val, w), _fmt_bits(mask, w)]
        lines.append(" ".join(fields))

    for ex in problem.examples:
        if not any(g.startswith(ex["check"]) for g in groups):
            raise ValueError(f"example check '{ex['check']}' matches no check name")

    tb = problem.path / "tb"
    tb.mkdir(exist_ok=True)
    (tb / "vectors.txt").write_text("\n".join(lines) + "\n")
    langs = problem.languages
    if any(LANGUAGES[l]["family"] == "verilog" for l in langs):
        (tb / "tb.sv").write_text(_sv(spec, groups, len(lines)))
    if "vhdl" in langs:
        (tb / "tb.vhd").write_text(_vhdl(spec, groups, len(lines)))
    written = _starters(problem, spec)
    from . import waves
    waves.build(problem, gen)
    return len(lines), groups, written


# ---------------------------------------------------------------- SystemVerilog

def _sv_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _sv_param(v):
    return str(v)


def _sv(spec, groups, nvec):
    p = spec.p
    L = [HEADER.rstrip(), "`timescale 1ns/1ps", "module tb;"]
    if spec.clock:
        L.append(f"    reg {spec.clock} = 1'b0;")
    for x in spec.ins:
        if spec.is_real(x):
            L.append(f"    real {x['name']} = 0.0;")
        # left at X on purpose: the first vector then always produces an event, so
        # always @(*) blocks are evaluated even when that vector is all zeros
        elif x["width"] == 1:
            L.append(f"    reg {x['name']};")
        else:
            L.append(f"    reg [{x['width'] - 1}:0] {x['name']};")
    for x in spec.outs:
        n = x["name"]
        if spec.is_real(x):
            L.append(f"    real {n};")
            L.append(f"    real e_{n};")
            L.append(f"    reg [3:0] m_{n};")
        else:
            rng = f"[{x['width'] - 1}:0] " if x["width"] > 1 else ""
            L.append(f"    wire {rng}{n};")
            L.append(f"    reg {rng}e_{n}, m_{n};")
    L += ["    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;",
          "    reg [8*400-1:0] tb_detail;", ""]

    params = ""
    if spec.params:
        params = " #(" + ", ".join(f".{k}({_sv_param(v)})" for k, v in spec.params.items()) + ")"
    conns = [spec.clock] if spec.clock else []
    conns += [x["name"] for x in spec.ins + spec.outs]
    L.append(f"    {p.top}{params} dut ({', '.join(f'.{c}({c})' for c in conns)});")
    L.append("")
    if spec.clock:
        L += [f"    always #5 {spec.clock} = ~{spec.clock};", ""]

    L.append("    function [8*120-1:0] tb_gname(input integer g);")
    L.append("        case (g)")
    for i, g in enumerate(groups):
        L.append(f"            {i}: tb_gname = {_sv_str(g)};")
    L += ['            default: tb_gname = "?";', "        endcase", "    endfunction", ""]

    L += ["    function real tb_abs(input real x);", "        tb_abs = x < 0.0 ? -x : x;",
          "    endfunction", "",
          "    task tb_end_group;", "        begin",
          '            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));',
          '            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);',
          "        end", "    endtask", ""]

    # check task
    bad = []
    for x in spec.outs:
        n = x["name"]
        if spec.is_real(x):
            tol = spec.tol.get(n, 1e-9)
            bad.append(f"(m_{n} != 0 && !(tb_abs({n} - e_{n}) <= {tol:.6e}))")
        else:
            bad.append(f"((({n} ^ e_{n}) & m_{n}) !== 0)")
    fmt_in = " ".join(f"{x['name']}=" + ("%g" if spec.is_real(x) else "%h") for x in spec.ins)
    fmt_exp = " ".join(f"{x['name']}=" + ("%g" if spec.is_real(x) else "%h") for x in spec.outs)
    args = [x["name"] for x in spec.ins] + [f"e_{x['name']}" for x in spec.outs] + \
           [x["name"] for x in spec.outs]
    L += ["    task tb_check;", "        begin",
          "            if (" + " ||\n                ".join(bad) + ") begin",
          "                if (tb_errors == 0)",
          f'                    $sformat(tb_detail, "vector %0d (t=%t): {fmt_in} -> expected {fmt_exp}, got {fmt_exp}",',
          f"                             tb_vec, $time, {', '.join(args)});",
          "                tb_errors = tb_errors + 1;", "            end", "        end", "    endtask", ""]

    scan_fmt = "%d" + "".join(" %f" if spec.is_real(x) else " %h" for x in spec.ins)
    scan_args = ["tb_grp"] + [x["name"] for x in spec.ins]
    for x in spec.outs:
        scan_fmt += " %f %h" if spec.is_real(x) else " %h %h"
        scan_args += [f"e_{x['name']}", f"m_{x['name']}"]
    nfields = len(scan_args)

    L += ["    initial begin",
          '        $timeformat(-9, 0, " ns", 0);',
          '        if ($test$plusargs("vcd")) begin',
          '            $dumpfile("wave.vcd");',
          "            $dumpvars(1, dut);",
          "        end",
          '        tb_fd = $fopen("vectors.txt", "r");',
          "        if (tb_fd == 0) begin",
          '            $display("FAIL: testbench could not open its vector file");',
          '            $display("TB_DONE");',
          "            $finish;",
          "        end",
          "        tb_cur = -1; tb_vec = 0; tb_errors = 0;"]
    L.append(f"        @(negedge {spec.clock});" if spec.clock else "        #1;")
    L.append(f'        while ($fscanf(tb_fd, "{scan_fmt}\\n", {", ".join(scan_args)}) == {nfields}) begin')
    L += ["            if (tb_grp != tb_cur) begin",
          "                if (tb_cur >= 0) tb_end_group;",
          '                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";',
          "            end"]
    if spec.clock:
        L += [f"            @(negedge {spec.clock});", "            tb_check;"]
    else:
        L += ["            #5;", "            tb_check;", "            #5;"]
    L += ["            tb_vec = tb_vec + 1;", "        end",
          "        if (tb_cur >= 0) tb_end_group;",
          f"        if (tb_vec != {nvec})",
          f'            $display("FAIL: testbench read %0d of {nvec} vectors", tb_vec);',
          '        $display("TB_DONE");', "        $finish;", "    end", "",
          "    initial begin",
          f"        #{nvec * 10 + 1000};",
          '        $display("FAIL: testbench watchdog expired");',
          "        $finish;", "    end", "endmodule", ""]
    return "\n".join(L)


# ---------------------------------------------------------------- VHDL

def _vhdl_str(s):
    return '"' + s.replace('"', '""') + '"'


def _vhdl(spec, groups, nvec):
    p = spec.p
    L = [HEADER.replace("//", "--").rstrip(), "library ieee;", "use ieee.std_logic_1164.all;",
         "use ieee.numeric_std.all;", "use std.textio.all;", "", "entity tb is", "end entity;", "",
         "architecture sim of tb is"]
    if spec.clock:
        L.append(f"    signal {spec.clock} : std_logic := '0';")
    for x in spec.ins:
        n, w = x["name"], x["width"]
        if spec.is_real(x):
            L.append(f"    signal {n} : real := 0.0;")
        elif w == 1:
            L.append(f"    signal {n} : std_logic := '0';")
        else:
            L.append(f"    signal {n} : std_logic_vector({w - 1} downto 0) := (others => '0');")
    for x in spec.outs:
        n, w = x["name"], x["width"]
        if spec.is_real(x):
            L.append(f"    signal {n} : real;")
        elif w == 1:
            L.append(f"    signal {n} : std_logic;")
        else:
            L.append(f"    signal {n} : std_logic_vector({w - 1} downto 0);")
    L += ["    signal tb_done : boolean := false;", "begin"]
    gmap = ""
    if spec.params:
        gmap = " generic map (" + ", ".join(f"{k} => {v}" for k, v in spec.params.items()) + ")"
    conns = ([spec.clock] if spec.clock else []) + [x["name"] for x in spec.ins + spec.outs]
    L.append(f"    dut : entity work.{p.top}{gmap}")
    L.append(f"        port map ({', '.join(f'{c} => {c}' for c in conns)});")
    L.append("")
    if spec.clock:
        L += [f"    {spec.clock} <= not {spec.clock} after 5 ns when not tb_done;", ""]

    L += ["    watchdog : process", "    begin",
          f"        wait for {nvec * 10 + 1000} ns;",
          '        report "FAIL: testbench watchdog expired";', "        std.env.finish;",
          "        wait;", "    end process;", "",
          "    stim : process",
          '        file tb_f : text open read_mode is "vectors.txt";',
          "        variable tb_l, tb_detail : line;",
          "        variable tb_grp : integer;",
          "        variable tb_cur : integer := -1;",
          "        variable tb_errors, tb_vec : natural := 0;",
          "        variable tb_bad : boolean;"]

    def vec_t(w):
        return f"std_logic_vector({w - 1} downto 0)"
    for x in spec.ins:
        L.append(f"        variable v_{x['name']} : {'real' if spec.is_real(x) else vec_t(x['width'])};")
    for x in spec.outs:
        n = x["name"]
        if spec.is_real(x):
            L.append(f"        variable e_{n} : real;")
            L.append(f"        variable m_{n} : std_logic_vector(3 downto 0);")
        else:
            L.append(f"        variable e_{n}, m_{n} : {vec_t(x['width'])};")
    L += ["", "        function tb_gname(g : integer) return string is", "        begin",
          "            case g is"]
    for i, g in enumerate(groups):
        L.append(f"                when {i} => return {_vhdl_str(g)};")
    L += ['                when others => return "?";', "            end case;", "        end function;", "",
          "        function tb_diff(got, exp, mask : std_logic_vector) return boolean is",
          "            alias g : std_logic_vector(got'length - 1 downto 0) is got;",
          "            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;",
          "            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;",
          "        begin",
          "            for i in e'range loop",
          "                if m(i) = '1' and g(i) /= e(i) then",
          "                    return true;", "                end if;", "            end loop;",
          "            return false;", "        end function;", "",
          "        procedure tb_end_group is", "        begin",
          "            if tb_errors = 0 then",
          '                report "PASS: " & tb_gname(tb_cur);',
          "            else",
          '                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &',
          '                       integer\'image(tb_errors) & " mismatches)";',
          "            end if;", "        end procedure;", "",
          "        function sv(s : std_logic) return std_logic_vector is", "        begin",
          "            return (0 => s);", "        end function;",
          "        function sv(s : std_logic_vector) return std_logic_vector is", "        begin",
          "            return s;", "        end function;", "    begin"]

    L.append(f"        wait until falling_edge({spec.clock});" if spec.clock else "        wait for 1 ns;")
    L += ["        while not endfile(tb_f) loop",
          "            readline(tb_f, tb_l);",
          "            next when tb_l'length = 0;",
          "            read(tb_l, tb_grp);"]
    for x in spec.ins:
        L.append(f"            {'read' if spec.is_real(x) else 'hread'}(tb_l, v_{x['name']});")
    for x in spec.outs:
        n = x["name"]
        L.append(f"            {'read' if spec.is_real(x) else 'hread'}(tb_l, e_{n});")
        L.append(f"            hread(tb_l, m_{n});")
    for x in spec.ins:
        n = x["name"]
        if spec.is_real(x) or x["width"] > 1:
            L.append(f"            {n} <= v_{n};")
        else:
            L.append(f"            {n} <= v_{n}(0);")
    L += ["            if tb_grp /= tb_cur then",
          "                if tb_cur >= 0 then", "                    tb_end_group;", "                end if;",
          "                tb_cur := tb_grp;", "                tb_errors := 0;",
          "                deallocate(tb_detail);", '                tb_detail := new string\'("");',
          "            end if;"]
    L.append(f"            wait until falling_edge({spec.clock});" if spec.clock else "            wait for 5 ns;")
    bad = []
    for x in spec.outs:
        n = x["name"]
        if spec.is_real(x):
            tol = spec.tol.get(n, 1e-9)
            bad.append(f"(m_{n}(0) = '1' and not (abs({n} - e_{n}) <= {tol:.6e}))")
        else:
            bad.append(f"tb_diff(sv({n}), e_{n}, m_{n})")
    L.append("            tb_bad := " + "\n                   or ".join(bad) + ";")

    def img_in(x):
        return f"real'image(v_{x['name']})" if spec.is_real(x) else f"to_hstring(v_{x['name']})"

    def img_exp(x):
        return f"real'image(e_{x['name']})" if spec.is_real(x) else f"to_hstring(e_{x['name']})"

    def img_got(x):
        return f"real'image({x['name']})" if spec.is_real(x) else f"to_hstring(sv({x['name']}))"
    ins_s = " & \" \" & ".join(f"\"{x['name']}=\" & {img_in(x)}" for x in spec.ins) or '""'
    exp_s = " & \" \" & ".join(f"\"{x['name']}=\" & {img_exp(x)}" for x in spec.outs)
    got_s = " & \" \" & ".join(f"\"{x['name']}=\" & {img_got(x)}" for x in spec.outs)
    L += ["            if tb_bad then",
          "                if tb_errors = 0 then",
          "                    deallocate(tb_detail);",
          '                    tb_detail := new string\'("vector " & integer\'image(tb_vec) & " (t=" & time\'image(now) & "): " &',
          f"                        {ins_s} &",
          f'                        " -> expected " & {exp_s} &',
          f'                        ", got " & {got_s});',
          "                end if;",
          "                tb_errors := tb_errors + 1;",
          "            end if;",
          "            tb_vec := tb_vec + 1;"]
    if not spec.clock:
        L.append("            wait for 5 ns;")
    L += ["        end loop;",
          "        if tb_cur >= 0 then", "            tb_end_group;", "        end if;",
          f"        if tb_vec /= {nvec} then",
          f'            report "FAIL: testbench read " & integer\'image(tb_vec) & " of {nvec} vectors";',
          "        end if;",
          '        report "TB_DONE";', "        tb_done <= true;", "        std.env.finish;", "        wait;",
          "    end process;", "end architecture;", ""]
    return "\n".join(L)


# ---------------------------------------------------------------- starters

def _starters(problem, spec):
    params = problem.meta.get("params", [])
    written = []
    all_ports = problem.ports
    for lang in problem.languages:
        f = problem.path / "starter" / (lang + LANGUAGES[lang]["ext"])
        if f.exists():
            continue
        f.parent.mkdir(exist_ok=True)
        f.write_text(_starter_vhdl(problem, params, all_ports) if lang == "vhdl"
                     else _starter_v(problem, params, all_ports, lang))
        written.append(f.name)
    return written


def _starter_v(problem, params, ports, lang):
    sv = lang == "systemverilog"
    t_in, t_out = ("logic", "logic") if sv else ("wire", "reg ")
    lines = []
    head = f"module {problem.top}"
    if params:
        ps = []
        for prm in params:
            kind = "real " if prm.get("type") == "real" else ("integer " if sv else "")
            ps.append(f"    parameter {kind}{prm['name']} = {prm['default']}")
        head += " #(\n" + ",\n".join(ps) + "\n)"
    if any(x.get("type") == "real" for x in ports) and problem.meta.get("timescale"):
        lines.append("`timescale 1ns / 1ps")
    lines.append(head + " (")
    decls = []
    width_col = max((len(f"[{x['width'] - 1}:0]") for x in ports if x["width"] > 1), default=0)
    for x in ports:
        d = "input " if x["dir"] == "input" else "output"
        init = ""
        if x.get("type") == "real":
            typ, rng = "real ", ""
            init = " = 0.0" if x["dir"] == "output" else ""
        else:
            typ = t_in if x["dir"] == "input" else t_out
            rng = f"[{x['width'] - 1}:0]" if x["width"] > 1 else ""
        decls.append(f"    {d} {typ} {rng.ljust(width_col)} {x['name']}{init}")
    lines.append(",\n".join(decls))
    lines += [");", "", "    // Your code here", "", "endmodule", ""]
    return "\n".join(lines)


def _starter_vhdl(problem, params, ports):
    lines = ["library ieee;", "use ieee.std_logic_1164.all;", "use ieee.numeric_std.all;"]
    if any(x.get("type") == "real" for x in ports) or any(p.get("type") == "real" for p in params):
        lines.append("use ieee.math_real.all;")
    lines += ["", f"entity {problem.top} is"]
    if params:
        gs = []
        for prm in params:
            t = "real" if prm.get("type") == "real" else "positive"
            gs.append(f"        {prm['name']} : {t} := {prm['default']}")
        lines += ["    generic (", ";\n".join(gs), "    );"]
    ps = []
    width = max(len(x["name"]) for x in ports)
    for x in ports:
        d = "in " if x["dir"] == "input" else "out"
        if x.get("type") == "real":
            t = "real := 0.0" if x["dir"] == "output" else "real"
        elif x["width"] == 1:
            t = "std_logic"
        else:
            t = f"std_logic_vector({x['width'] - 1} downto 0)"
        ps.append(f"        {x['name'].ljust(width)} : {d} {t}")
    lines += ["    port (", ";\n".join(ps), "    );", "end entity;", "",
              f"architecture {'behavioral' if problem.category == 'modeling' else 'rtl'} of {problem.top} is",
              "begin", "", "    -- Your code here", "", "end architecture;", ""]
    return "\n".join(lines)
