-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal bin : std_logic_vector(7 downto 0) := (others => '0');
    signal gray_in : std_logic_vector(7 downto 0) := (others => '0');
    signal gray : std_logic_vector(7 downto 0);
    signal bin_out : std_logic_vector(7 downto 0);
    signal tb_done : boolean := false;
begin
    dut : entity work.gray_conv
        port map (bin => bin, gray_in => gray_in, gray => gray, bin_out => bin_out);

    watchdog : process
    begin
        wait for 8120 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_bin : std_logic_vector(7 downto 0);
        variable v_gray_in : std_logic_vector(7 downto 0);
        variable e_gray, m_gray : std_logic_vector(7 downto 0);
        variable e_bin_out, m_bin_out : std_logic_vector(7 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "binary to Gray (all 256 values)";
                when 1 => return "Gray to binary (all 256 values)";
                when 2 => return "round trip bin -> Gray -> bin";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait for 1 ns;
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_bin);
            hread(tb_l, v_gray_in);
            hread(tb_l, e_gray);
            hread(tb_l, m_gray);
            hread(tb_l, e_bin_out);
            hread(tb_l, m_bin_out);
            bin <= v_bin;
            gray_in <= v_gray_in;
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait for 5 ns;
            tb_bad := tb_diff(sv(gray), e_gray, m_gray)
                   or tb_diff(sv(bin_out), e_bin_out, m_bin_out);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "bin=" & to_hstring(v_bin) & " " & "gray_in=" & to_hstring(v_gray_in) &
                        " -> expected " & "gray=" & to_hstring(e_gray) & " " & "bin_out=" & to_hstring(e_bin_out) &
                        ", got " & "gray=" & to_hstring(sv(gray)) & " " & "bin_out=" & to_hstring(sv(bin_out)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
            wait for 5 ns;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 712 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 712 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
