// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    real vin = 0.0;
    real vout;
    real e_vout;
    reg [3:0] m_vout;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    slew_limiter #(.SR(2.0e7)) dut (.clk(clk), .vin(vin), .vout(vout));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "large step is rate-limited";
            1: tb_gname = "small changes pass through";
            2: tb_gname = "falling step";
            3: tb_gname = "1500 steps: slow sine passes, fast sine is slew-limited";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((m_vout != 0 && !(tb_abs(vout - e_vout) <= 1.000000e-09))) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): vin=%g -> expected vout=%g, got vout=%g",
                             tb_vec, $time, vin, e_vout, vout);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %f %f %h\n", tb_grp, vin, e_vout, m_vout) == 4) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 1521)
            $display("FAIL: testbench read %0d of 1521 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #16210;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
