// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg car;
    wire [1:0] main;
    reg [1:0] e_main, m_main;
    wire [1:0] side;
    reg [1:0] e_side, m_side;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    traffic_light dut (.clk(clk), .rst(rst), .car(car), .main(main), .side(side));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "waits for a car on the side street";
            1: tb_gname = "full cycle with a car always waiting";
            2: tb_gname = "minimum green time is enforced";
            3: tb_gname = "reset in the middle of a cycle";
            4: tb_gname = "1500 cycles of random traffic";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((main ^ e_main) & m_main) !== 0) ||
                (((side ^ e_side) & m_side) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h car=%h -> expected main=%h side=%h, got main=%h side=%h",
                             tb_vec, $time, rst, car, e_main, e_side, main, side);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h\n", tb_grp, rst, car, e_main, m_main, e_side, m_side) == 7) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 1623)
            $display("FAIL: testbench read %0d of 1623 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #17230;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
