-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal clk : std_logic := '0';
    signal rst : std_logic := '0';
    signal stall : std_logic := '0';
    signal valid_in : std_logic := '0';
    signal op : std_logic_vector(1 downto 0) := (others => '0');
    signal a : std_logic_vector(15 downto 0) := (others => '0');
    signal b : std_logic_vector(15 downto 0) := (others => '0');
    signal valid_out : std_logic;
    signal y : std_logic_vector(15 downto 0);
    signal zero : std_logic;
    signal tb_done : boolean := false;
begin
    dut : entity work.pipe_alu
        port map (clk => clk, rst => rst, stall => stall, valid_in => valid_in, op => op, a => a, b => b, valid_out => valid_out, y => y, zero => zero);

    clk <= not clk after 5 ns when not tb_done;

    watchdog : process
    begin
        wait for 26200 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_rst : std_logic_vector(0 downto 0);
        variable v_stall : std_logic_vector(0 downto 0);
        variable v_valid_in : std_logic_vector(0 downto 0);
        variable v_op : std_logic_vector(1 downto 0);
        variable v_a : std_logic_vector(15 downto 0);
        variable v_b : std_logic_vector(15 downto 0);
        variable e_valid_out, m_valid_out : std_logic_vector(0 downto 0);
        variable e_y, m_y : std_logic_vector(15 downto 0);
        variable e_zero, m_zero : std_logic_vector(0 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "latency 2";
                when 1 => return "stall freezes the pipeline";
                when 2 => return "bubbles flow through";
                when 3 => return "2500 random cycles";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait until falling_edge(clk);
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_rst);
            hread(tb_l, v_stall);
            hread(tb_l, v_valid_in);
            hread(tb_l, v_op);
            hread(tb_l, v_a);
            hread(tb_l, v_b);
            hread(tb_l, e_valid_out);
            hread(tb_l, m_valid_out);
            hread(tb_l, e_y);
            hread(tb_l, m_y);
            hread(tb_l, e_zero);
            hread(tb_l, m_zero);
            rst <= v_rst(0);
            stall <= v_stall(0);
            valid_in <= v_valid_in(0);
            op <= v_op;
            a <= v_a;
            b <= v_b;
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait until falling_edge(clk);
            tb_bad := tb_diff(sv(valid_out), e_valid_out, m_valid_out)
                   or tb_diff(sv(y), e_y, m_y)
                   or tb_diff(sv(zero), e_zero, m_zero);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "rst=" & to_hstring(v_rst) & " " & "stall=" & to_hstring(v_stall) & " " & "valid_in=" & to_hstring(v_valid_in) & " " & "op=" & to_hstring(v_op) & " " & "a=" & to_hstring(v_a) & " " & "b=" & to_hstring(v_b) &
                        " -> expected " & "valid_out=" & to_hstring(e_valid_out) & " " & "y=" & to_hstring(e_y) & " " & "zero=" & to_hstring(e_zero) &
                        ", got " & "valid_out=" & to_hstring(sv(valid_out)) & " " & "y=" & to_hstring(sv(y)) & " " & "zero=" & to_hstring(sv(zero)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 2520 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 2520 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
