// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg [7:0] pc;
    reg update;
    reg [7:0] upd_pc;
    reg taken;
    wire pred;
    reg e_pred, m_pred;
    wire [1:0] ctr;
    reg [1:0] e_ctr, m_ctr;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    bht dut (.clk(clk), .rst(rst), .pc(pc), .update(update), .upd_pc(upd_pc), .taken(taken), .pred(pred), .ctr(ctr));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "learns a taken branch";
            1: tb_gname = "hysteresis: one mispredict does not flip";
            2: tb_gname = "aliasing: pc[5:2] indexes the table";
            3: tb_gname = "3000 random branches";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((pred ^ e_pred) & m_pred) !== 0) ||
                (((ctr ^ e_ctr) & m_ctr) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h pc=%h update=%h upd_pc=%h taken=%h -> expected pred=%h ctr=%h, got pred=%h ctr=%h",
                             tb_vec, $time, rst, pc, update, upd_pc, taken, e_pred, e_ctr, pred, ctr);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, pc, update, upd_pc, taken, e_pred, m_pred, e_ctr, m_ctr) == 10) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3013)
            $display("FAIL: testbench read %0d of 3013 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #31130;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
