// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    logic clk = 1'b0;
    logic rst = 1'b1;
    logic [2:0] lock_req = '0;
    logic [2:0] lock_gnt = '0;
    int trace;

    chk_lock dut (.clk(clk), .rst(rst), .lock_req(lock_req), .lock_gnt(lock_gnt));

    always #5 clk = ~clk;

    initial begin
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        if (!$value$plusargs("trace=%d", trace)) trace = 0;
        case (trace)
            0: begin
                @(negedge clk); rst = 1'd1; lock_req = 3'd0; lock_gnt = 3'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); lock_req = 3'd1; lock_gnt = 3'd1;
                @(negedge clk); lock_req = 3'd5;
                @(negedge clk); 
                @(negedge clk); lock_req = 3'd4;
                @(negedge clk); lock_gnt = 3'd4;
                @(negedge clk); lock_req = 3'd0;
                @(negedge clk); lock_gnt = 3'd0;
            end
            1: begin
                @(negedge clk); rst = 1'd1; lock_req = 3'd0; lock_gnt = 3'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); lock_req = 3'd5; lock_gnt = 3'd5;
            end
            2: begin
                @(negedge clk); rst = 1'd1; lock_req = 3'd0; lock_gnt = 3'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); lock_req = 3'd1; lock_gnt = 3'd2;
            end
            3: begin
                @(negedge clk); rst = 1'd1; lock_req = 3'd0; lock_gnt = 3'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); lock_req = 3'd3; lock_gnt = 3'd1;
                @(negedge clk); lock_gnt = 3'd2;
                @(negedge clk); 
            end
            default: ;
        endcase
        repeat (3) @(negedge clk);
        $display("TRACE_DONE");
        $finish;
    end
endmodule
