// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg rx;
    wire [7:0] data;
    reg [7:0] e_data, m_data;
    wire valid;
    reg e_valid, m_valid;
    wire frame_err;
    reg e_frame_err, m_frame_err;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    uart_rx dut (.clk(clk), .rst(rst), .rx(rx), .data(data), .valid(valid), .frame_err(frame_err));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "reset and idle line";
            1: tb_gname = "single frame 0xA5";
            2: tb_gname = "glitch on the idle line is not a start bit";
            3: tb_gname = "framing error (stop bit = 0)";
            4: tb_gname = "back-to-back frames";
            5: tb_gname = "clock mismatch: bits 7 and 9 cycles long";
            6: tb_gname = "40 random frames with gaps, glitches and bad stop bits";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((data ^ e_data) & m_data) !== 0) ||
                (((valid ^ e_valid) & m_valid) !== 0) ||
                (((frame_err ^ e_frame_err) & m_frame_err) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h rx=%h -> expected data=%h valid=%h frame_err=%h, got data=%h valid=%h frame_err=%h",
                             tb_vec, $time, rst, rx, e_data, e_valid, e_frame_err, data, valid, frame_err);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h\n", tb_grp, rst, rx, e_data, m_data, e_valid, m_valid, e_frame_err, m_frame_err) == 9) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 4458)
            $display("FAIL: testbench read %0d of 4458 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #45580;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
