-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal clk : std_logic := '0';
    signal rst : std_logic := '0';
    signal rx : std_logic := '0';
    signal data : std_logic_vector(7 downto 0);
    signal valid : std_logic;
    signal frame_err : std_logic;
    signal tb_done : boolean := false;
begin
    dut : entity work.uart_rx
        port map (clk => clk, rst => rst, rx => rx, data => data, valid => valid, frame_err => frame_err);

    clk <= not clk after 5 ns when not tb_done;

    watchdog : process
    begin
        wait for 45580 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_rst : std_logic_vector(0 downto 0);
        variable v_rx : std_logic_vector(0 downto 0);
        variable e_data, m_data : std_logic_vector(7 downto 0);
        variable e_valid, m_valid : std_logic_vector(0 downto 0);
        variable e_frame_err, m_frame_err : std_logic_vector(0 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "reset and idle line";
                when 1 => return "single frame 0xA5";
                when 2 => return "glitch on the idle line is not a start bit";
                when 3 => return "framing error (stop bit = 0)";
                when 4 => return "back-to-back frames";
                when 5 => return "clock mismatch: bits 7 and 9 cycles long";
                when 6 => return "40 random frames with gaps, glitches and bad stop bits";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait until falling_edge(clk);
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_rst);
            hread(tb_l, v_rx);
            hread(tb_l, e_data);
            hread(tb_l, m_data);
            hread(tb_l, e_valid);
            hread(tb_l, m_valid);
            hread(tb_l, e_frame_err);
            hread(tb_l, m_frame_err);
            rst <= v_rst(0);
            rx <= v_rx(0);
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait until falling_edge(clk);
            tb_bad := tb_diff(sv(data), e_data, m_data)
                   or tb_diff(sv(valid), e_valid, m_valid)
                   or tb_diff(sv(frame_err), e_frame_err, m_frame_err);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "rst=" & to_hstring(v_rst) & " " & "rx=" & to_hstring(v_rx) &
                        " -> expected " & "data=" & to_hstring(e_data) & " " & "valid=" & to_hstring(e_valid) & " " & "frame_err=" & to_hstring(e_frame_err) &
                        ", got " & "data=" & to_hstring(sv(data)) & " " & "valid=" & to_hstring(sv(valid)) & " " & "frame_err=" & to_hstring(sv(frame_err)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 4458 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 4458 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
