-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal code : std_logic_vector(7 downto 0) := (others => '0');
    signal data : std_logic_vector(3 downto 0);
    signal single_err : std_logic;
    signal double_err : std_logic;
    signal tb_done : boolean := false;
begin
    dut : entity work.secded_dec
        port map (code => code, data => data, single_err => single_err, double_err => double_err);

    watchdog : process
    begin
        wait for 6920 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_code : std_logic_vector(7 downto 0);
        variable e_data, m_data : std_logic_vector(3 downto 0);
        variable e_single_err, m_single_err : std_logic_vector(0 downto 0);
        variable e_double_err, m_double_err : std_logic_vector(0 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "clean code words (all 16)";
                when 1 => return "single-bit errors (16 x 8)";
                when 2 => return "double-bit errors (16 x 28)";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait for 1 ns;
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_code);
            hread(tb_l, e_data);
            hread(tb_l, m_data);
            hread(tb_l, e_single_err);
            hread(tb_l, m_single_err);
            hread(tb_l, e_double_err);
            hread(tb_l, m_double_err);
            code <= v_code;
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait for 5 ns;
            tb_bad := tb_diff(sv(data), e_data, m_data)
                   or tb_diff(sv(single_err), e_single_err, m_single_err)
                   or tb_diff(sv(double_err), e_double_err, m_double_err);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "code=" & to_hstring(v_code) &
                        " -> expected " & "data=" & to_hstring(e_data) & " " & "single_err=" & to_hstring(e_single_err) & " " & "double_err=" & to_hstring(e_double_err) &
                        ", got " & "data=" & to_hstring(sv(data)) & " " & "single_err=" & to_hstring(sv(single_err)) & " " & "double_err=" & to_hstring(sv(double_err)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
            wait for 5 ns;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 592 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 592 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
