-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal ex_rs1 : std_logic_vector(4 downto 0) := (others => '0');
    signal ex_rs2 : std_logic_vector(4 downto 0) := (others => '0');
    signal mem_rd : std_logic_vector(4 downto 0) := (others => '0');
    signal mem_reg_write : std_logic := '0';
    signal wb_rd : std_logic_vector(4 downto 0) := (others => '0');
    signal wb_reg_write : std_logic := '0';
    signal fwd_a : std_logic_vector(1 downto 0);
    signal fwd_b : std_logic_vector(1 downto 0);
    signal tb_done : boolean := false;
begin
    dut : entity work.forwarding_unit
        port map (ex_rs1 => ex_rs1, ex_rs2 => ex_rs2, mem_rd => mem_rd, mem_reg_write => mem_reg_write, wb_rd => wb_rd, wb_reg_write => wb_reg_write, fwd_a => fwd_a, fwd_b => fwd_b);

    watchdog : process
    begin
        wait for 31110 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_ex_rs1 : std_logic_vector(4 downto 0);
        variable v_ex_rs2 : std_logic_vector(4 downto 0);
        variable v_mem_rd : std_logic_vector(4 downto 0);
        variable v_mem_reg_write : std_logic_vector(0 downto 0);
        variable v_wb_rd : std_logic_vector(4 downto 0);
        variable v_wb_reg_write : std_logic_vector(0 downto 0);
        variable e_fwd_a, m_fwd_a : std_logic_vector(1 downto 0);
        variable e_fwd_b, m_fwd_b : std_logic_vector(1 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "EX/MEM forwarding";
                when 1 => return "MEM/WB forwarding";
                when 2 => return "priority: EX/MEM beats MEM/WB";
                when 3 => return "never forward x0 or non-writing stages";
                when 4 => return "3000 random pipeline states";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait for 1 ns;
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_ex_rs1);
            hread(tb_l, v_ex_rs2);
            hread(tb_l, v_mem_rd);
            hread(tb_l, v_mem_reg_write);
            hread(tb_l, v_wb_rd);
            hread(tb_l, v_wb_reg_write);
            hread(tb_l, e_fwd_a);
            hread(tb_l, m_fwd_a);
            hread(tb_l, e_fwd_b);
            hread(tb_l, m_fwd_b);
            ex_rs1 <= v_ex_rs1;
            ex_rs2 <= v_ex_rs2;
            mem_rd <= v_mem_rd;
            mem_reg_write <= v_mem_reg_write(0);
            wb_rd <= v_wb_rd;
            wb_reg_write <= v_wb_reg_write(0);
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait for 5 ns;
            tb_bad := tb_diff(sv(fwd_a), e_fwd_a, m_fwd_a)
                   or tb_diff(sv(fwd_b), e_fwd_b, m_fwd_b);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "ex_rs1=" & to_hstring(v_ex_rs1) & " " & "ex_rs2=" & to_hstring(v_ex_rs2) & " " & "mem_rd=" & to_hstring(v_mem_rd) & " " & "mem_reg_write=" & to_hstring(v_mem_reg_write) & " " & "wb_rd=" & to_hstring(v_wb_rd) & " " & "wb_reg_write=" & to_hstring(v_wb_reg_write) &
                        " -> expected " & "fwd_a=" & to_hstring(e_fwd_a) & " " & "fwd_b=" & to_hstring(e_fwd_b) &
                        ", got " & "fwd_a=" & to_hstring(sv(fwd_a)) & " " & "fwd_b=" & to_hstring(sv(fwd_b)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
            wait for 5 ns;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 3011 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 3011 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
