-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal clk : std_logic := '0';
    signal rst : std_logic := '0';
    signal alloc_valid : std_logic := '0';
    signal alloc_rd : std_logic_vector(4 downto 0) := (others => '0');
    signal complete_valid : std_logic := '0';
    signal complete_tag : std_logic_vector(2 downto 0) := (others => '0');
    signal complete_data : std_logic_vector(15 downto 0) := (others => '0');
    signal alloc_ok : std_logic;
    signal alloc_tag : std_logic_vector(2 downto 0);
    signal commit_valid : std_logic;
    signal commit_rd : std_logic_vector(4 downto 0);
    signal commit_data : std_logic_vector(15 downto 0);
    signal count : std_logic_vector(3 downto 0);
    signal tb_done : boolean := false;
begin
    dut : entity work.rob8
        port map (clk => clk, rst => rst, alloc_valid => alloc_valid, alloc_rd => alloc_rd, complete_valid => complete_valid, complete_tag => complete_tag, complete_data => complete_data, alloc_ok => alloc_ok, alloc_tag => alloc_tag, commit_valid => commit_valid, commit_rd => commit_rd, commit_data => commit_data, count => count);

    clk <= not clk after 5 ns when not tb_done;

    watchdog : process
    begin
        wait for 31200 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_rst : std_logic_vector(0 downto 0);
        variable v_alloc_valid : std_logic_vector(0 downto 0);
        variable v_alloc_rd : std_logic_vector(4 downto 0);
        variable v_complete_valid : std_logic_vector(0 downto 0);
        variable v_complete_tag : std_logic_vector(2 downto 0);
        variable v_complete_data : std_logic_vector(15 downto 0);
        variable e_alloc_ok, m_alloc_ok : std_logic_vector(0 downto 0);
        variable e_alloc_tag, m_alloc_tag : std_logic_vector(2 downto 0);
        variable e_commit_valid, m_commit_valid : std_logic_vector(0 downto 0);
        variable e_commit_rd, m_commit_rd : std_logic_vector(4 downto 0);
        variable e_commit_data, m_commit_data : std_logic_vector(15 downto 0);
        variable e_count, m_count : std_logic_vector(3 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "reset";
                when 1 => return "allocate in order";
                when 2 => return "in-order commit after out-of-order completion";
                when 3 => return "full ROB rejects allocation";
                when 4 => return "3000 random cycles";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait until falling_edge(clk);
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_rst);
            hread(tb_l, v_alloc_valid);
            hread(tb_l, v_alloc_rd);
            hread(tb_l, v_complete_valid);
            hread(tb_l, v_complete_tag);
            hread(tb_l, v_complete_data);
            hread(tb_l, e_alloc_ok);
            hread(tb_l, m_alloc_ok);
            hread(tb_l, e_alloc_tag);
            hread(tb_l, m_alloc_tag);
            hread(tb_l, e_commit_valid);
            hread(tb_l, m_commit_valid);
            hread(tb_l, e_commit_rd);
            hread(tb_l, m_commit_rd);
            hread(tb_l, e_commit_data);
            hread(tb_l, m_commit_data);
            hread(tb_l, e_count);
            hread(tb_l, m_count);
            rst <= v_rst(0);
            alloc_valid <= v_alloc_valid(0);
            alloc_rd <= v_alloc_rd;
            complete_valid <= v_complete_valid(0);
            complete_tag <= v_complete_tag;
            complete_data <= v_complete_data;
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait until falling_edge(clk);
            tb_bad := tb_diff(sv(alloc_ok), e_alloc_ok, m_alloc_ok)
                   or tb_diff(sv(alloc_tag), e_alloc_tag, m_alloc_tag)
                   or tb_diff(sv(commit_valid), e_commit_valid, m_commit_valid)
                   or tb_diff(sv(commit_rd), e_commit_rd, m_commit_rd)
                   or tb_diff(sv(commit_data), e_commit_data, m_commit_data)
                   or tb_diff(sv(count), e_count, m_count);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "rst=" & to_hstring(v_rst) & " " & "alloc_valid=" & to_hstring(v_alloc_valid) & " " & "alloc_rd=" & to_hstring(v_alloc_rd) & " " & "complete_valid=" & to_hstring(v_complete_valid) & " " & "complete_tag=" & to_hstring(v_complete_tag) & " " & "complete_data=" & to_hstring(v_complete_data) &
                        " -> expected " & "alloc_ok=" & to_hstring(e_alloc_ok) & " " & "alloc_tag=" & to_hstring(e_alloc_tag) & " " & "commit_valid=" & to_hstring(e_commit_valid) & " " & "commit_rd=" & to_hstring(e_commit_rd) & " " & "commit_data=" & to_hstring(e_commit_data) & " " & "count=" & to_hstring(e_count) &
                        ", got " & "alloc_ok=" & to_hstring(sv(alloc_ok)) & " " & "alloc_tag=" & to_hstring(sv(alloc_tag)) & " " & "commit_valid=" & to_hstring(sv(commit_valid)) & " " & "commit_rd=" & to_hstring(sv(commit_rd)) & " " & "commit_data=" & to_hstring(sv(commit_data)) & " " & "count=" & to_hstring(sv(count)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 3020 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 3020 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
