// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg pwr_on;
    reg save;
    reg restore;
    reg en;
    reg [7:0] d;
    wire [7:0] q_out;
    reg [7:0] e_q_out, m_q_out;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    ret_reg dut (.clk(clk), .rst(rst), .pwr_on(pwr_on), .save(save), .restore(restore), .en(en), .d(d), .q_out(q_out));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "normal register";
            1: tb_gname = "save, power off, restore";
            2: tb_gname = "state is lost without retention";
            3: tb_gname = "save is ignored while off";
            4: tb_gname = "3000 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((q_out ^ e_q_out) & m_q_out) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h pwr_on=%h save=%h restore=%h en=%h d=%h -> expected q_out=%h, got q_out=%h",
                             tb_vec, $time, rst, pwr_on, save, restore, en, d, e_q_out, q_out);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h\n", tb_grp, rst, pwr_on, save, restore, en, d, e_q_out, m_q_out) == 9) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3018)
            $display("FAIL: testbench read %0d of 3018 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #31180;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
