// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg [15:0] x;
    wire [15:0] iso;
    reg [15:0] e_iso, m_iso;
    wire [15:0] clr;
    reg [15:0] e_clr, m_clr;
    wire [15:0] tmask;
    reg [15:0] e_tmask, m_tmask;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    lsb_tricks dut (.x(x), .iso(iso), .clr(clr), .tmask(tmask));

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "zero";
            1: tb_gname = "worked examples";
            2: tb_gname = "3000 random";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((iso ^ e_iso) & m_iso) !== 0) ||
                (((clr ^ e_clr) & m_clr) !== 0) ||
                (((tmask ^ e_tmask) & m_tmask) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): x=%h -> expected iso=%h clr=%h tmask=%h, got iso=%h clr=%h tmask=%h",
                             tb_vec, $time, x, e_iso, e_clr, e_tmask, iso, clr, tmask);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        #1;
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h\n", tb_grp, x, e_iso, m_iso, e_clr, m_clr, e_tmask, m_tmask) == 8) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            #5;
            tb_check;
            #5;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3006)
            $display("FAIL: testbench read %0d of 3006 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #31060;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
