// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg [4:0] id_rs1;
    reg [4:0] id_rs2;
    reg id_uses_rs1;
    reg id_uses_rs2;
    reg [4:0] ex_rd;
    reg ex_mem_read;
    reg ex_branch_taken;
    wire stall;
    reg e_stall, m_stall;
    wire id_ex_bubble;
    reg e_id_ex_bubble, m_id_ex_bubble;
    wire if_id_flush;
    reg e_if_id_flush, m_if_id_flush;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    hazard_unit dut (.id_rs1(id_rs1), .id_rs2(id_rs2), .id_uses_rs1(id_uses_rs1), .id_uses_rs2(id_uses_rs2), .ex_rd(ex_rd), .ex_mem_read(ex_mem_read), .ex_branch_taken(ex_branch_taken), .stall(stall), .id_ex_bubble(id_ex_bubble), .if_id_flush(if_id_flush));

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "load-use stall";
            1: tb_gname = "no hazard: x0, non-load, unused operand, different register";
            2: tb_gname = "taken branch squashes and wins over stall";
            3: tb_gname = "3000 random pipeline states";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((stall ^ e_stall) & m_stall) !== 0) ||
                (((id_ex_bubble ^ e_id_ex_bubble) & m_id_ex_bubble) !== 0) ||
                (((if_id_flush ^ e_if_id_flush) & m_if_id_flush) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): id_rs1=%h id_rs2=%h id_uses_rs1=%h id_uses_rs2=%h ex_rd=%h ex_mem_read=%h ex_branch_taken=%h -> expected stall=%h id_ex_bubble=%h if_id_flush=%h, got stall=%h id_ex_bubble=%h if_id_flush=%h",
                             tb_vec, $time, id_rs1, id_rs2, id_uses_rs1, id_uses_rs2, ex_rd, ex_mem_read, ex_branch_taken, e_stall, e_id_ex_bubble, e_if_id_flush, stall, id_ex_bubble, if_id_flush);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        #1;
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, id_rs1, id_rs2, id_uses_rs1, id_uses_rs2, ex_rd, ex_mem_read, ex_branch_taken, e_stall, m_stall, e_id_ex_bubble, m_id_ex_bubble, e_if_id_flush, m_if_id_flush) == 14) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            #5;
            tb_check;
            #5;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3010)
            $display("FAIL: testbench read %0d of 3010 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #31100;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
