// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg we;
    reg [1:0] waddr;
    reg [3:0] wbe;
    reg [31:0] wdata;
    reg [1:0] raddr;
    wire [31:0] rdata;
    reg [31:0] e_rdata, m_rdata;
    wire [15:0] cg_en;
    reg [15:0] e_cg_en, m_cg_en;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    byte_rf dut (.clk(clk), .rst(rst), .we(we), .waddr(waddr), .wbe(wbe), .wdata(wdata), .raddr(raddr), .rdata(rdata), .cg_en(cg_en));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "full writes";
            1: tb_gname = "byte enables";
            2: tb_gname = "clock enables";
            3: tb_gname = "2500 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((rdata ^ e_rdata) & m_rdata) !== 0) ||
                (((cg_en ^ e_cg_en) & m_cg_en) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h we=%h waddr=%h wbe=%h wdata=%h raddr=%h -> expected rdata=%h cg_en=%h, got rdata=%h cg_en=%h",
                             tb_vec, $time, rst, we, waddr, wbe, wdata, raddr, e_rdata, e_cg_en, rdata, cg_en);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, we, waddr, wbe, wdata, raddr, e_rdata, m_rdata, e_cg_en, m_cg_en) == 11) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 2511)
            $display("FAIL: testbench read %0d of 2511 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #26110;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
