// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg [19:0] tag;
    reg [79:0] way_tags;
    reg [3:0] way_valid;
    wire hit;
    reg e_hit, m_hit;
    wire [1:0] hit_way;
    reg [1:0] e_hit_way, m_hit_way;
    wire [3:0] hit_onehot;
    reg [3:0] e_hit_onehot, m_hit_onehot;
    wire multi_hit;
    reg e_multi_hit, m_multi_hit;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    tag_compare dut (.tag(tag), .way_tags(way_tags), .way_valid(way_valid), .hit(hit), .hit_way(hit_way), .hit_onehot(hit_onehot), .multi_hit(multi_hit));

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "hits in every way";
            1: tb_gname = "invalid ways never hit";
            2: tb_gname = "multi-hit detection";
            3: tb_gname = "3000 random lookups";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((hit ^ e_hit) & m_hit) !== 0) ||
                (((hit_way ^ e_hit_way) & m_hit_way) !== 0) ||
                (((hit_onehot ^ e_hit_onehot) & m_hit_onehot) !== 0) ||
                (((multi_hit ^ e_multi_hit) & m_multi_hit) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): tag=%h way_tags=%h way_valid=%h -> expected hit=%h hit_way=%h hit_onehot=%h multi_hit=%h, got hit=%h hit_way=%h hit_onehot=%h multi_hit=%h",
                             tb_vec, $time, tag, way_tags, way_valid, e_hit, e_hit_way, e_hit_onehot, e_multi_hit, hit, hit_way, hit_onehot, multi_hit);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        #1;
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, tag, way_tags, way_valid, e_hit, m_hit, e_hit_way, m_hit_way, e_hit_onehot, m_hit_onehot, e_multi_hit, m_multi_hit) == 12) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            #5;
            tb_check;
            #5;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3011)
            $display("FAIL: testbench read %0d of 3011 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #31110;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
