-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal clk : std_logic := '0';
    signal rst : std_logic := '0';
    signal start : std_logic := '0';
    signal data : std_logic_vector(7 downto 0) := (others => '0');
    signal tx : std_logic;
    signal busy : std_logic;
    signal tb_done : boolean := false;
begin
    dut : entity work.uart_tx
        port map (clk => clk, rst => rst, start => start, data => data, tx => tx, busy => busy);

    clk <= not clk after 5 ns when not tb_done;

    watchdog : process
    begin
        wait for 33500 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_rst : std_logic_vector(0 downto 0);
        variable v_start : std_logic_vector(0 downto 0);
        variable v_data : std_logic_vector(7 downto 0);
        variable e_tx, m_tx : std_logic_vector(0 downto 0);
        variable e_busy, m_busy : std_logic_vector(0 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "idle after reset";
                when 1 => return "single frame 0x55";
                when 2 => return "start ignored while busy";
                when 3 => return "back-to-back frames with start held high";
                when 4 => return "reset aborts a frame";
                when 5 => return "3000 cycles of random traffic";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait until falling_edge(clk);
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_rst);
            hread(tb_l, v_start);
            hread(tb_l, v_data);
            hread(tb_l, e_tx);
            hread(tb_l, m_tx);
            hread(tb_l, e_busy);
            hread(tb_l, m_busy);
            rst <= v_rst(0);
            start <= v_start(0);
            data <= v_data;
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait until falling_edge(clk);
            tb_bad := tb_diff(sv(tx), e_tx, m_tx)
                   or tb_diff(sv(busy), e_busy, m_busy);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "rst=" & to_hstring(v_rst) & " " & "start=" & to_hstring(v_start) & " " & "data=" & to_hstring(v_data) &
                        " -> expected " & "tx=" & to_hstring(e_tx) & " " & "busy=" & to_hstring(e_busy) &
                        ", got " & "tx=" & to_hstring(sv(tx)) & " " & "busy=" & to_hstring(sv(busy)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 3250 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 3250 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
