// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg req;
    reg [5:0] addr;
    wire pred;
    reg e_pred, m_pred;
    wire fast_hit;
    reg e_fast_hit, m_fast_hit;
    wire slow_hit;
    reg e_slow_hit, m_slow_hit;
    wire miss;
    reg e_miss, m_miss;
    wire [15:0] tag_reads;
    reg [15:0] e_tag_reads, m_tag_reads;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    way_pred dut (.clk(clk), .rst(rst), .req(req), .addr(addr), .pred(pred), .fast_hit(fast_hit), .slow_hit(slow_hit), .miss(miss), .tag_reads(tag_reads));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "predicted way hits";
            1: tb_gname = "mispredict costs a second probe";
            2: tb_gname = "replacement of the non-MRU way";
            3: tb_gname = "3000 random accesses";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((pred ^ e_pred) & m_pred) !== 0) ||
                (((fast_hit ^ e_fast_hit) & m_fast_hit) !== 0) ||
                (((slow_hit ^ e_slow_hit) & m_slow_hit) !== 0) ||
                (((miss ^ e_miss) & m_miss) !== 0) ||
                (((tag_reads ^ e_tag_reads) & m_tag_reads) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h req=%h addr=%h -> expected pred=%h fast_hit=%h slow_hit=%h miss=%h tag_reads=%h, got pred=%h fast_hit=%h slow_hit=%h miss=%h tag_reads=%h",
                             tb_vec, $time, rst, req, addr, e_pred, e_fast_hit, e_slow_hit, e_miss, e_tag_reads, pred, fast_hit, slow_hit, miss, tag_reads);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, req, addr, e_pred, m_pred, e_fast_hit, m_fast_hit, e_slow_hit, m_slow_hit, e_miss, m_miss, e_tag_reads, m_tag_reads) == 14) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3011)
            $display("FAIL: testbench read %0d of 3011 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #31110;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
