// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg pr_rd;
    reg pr_wr;
    reg bus_rd;
    reg bus_rdx;
    reg shared_in;
    wire [1:0] state;
    reg [1:0] e_state, m_state;
    wire wb;
    reg e_wb, m_wb;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    mesi_line dut (.clk(clk), .rst(rst), .pr_rd(pr_rd), .pr_wr(pr_wr), .bus_rd(bus_rd), .bus_rdx(bus_rdx), .shared_in(shared_in), .state(state), .wb(wb));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "reset goes to Invalid";
            1: tb_gname = "Invalid + local read, not shared -> Exclusive";
            2: tb_gname = "Exclusive + local read -> stays Exclusive";
            3: tb_gname = "back to Invalid";
            4: tb_gname = "Invalid + local read, shared -> Shared";
            5: tb_gname = "Shared + local read -> stays Shared";
            6: tb_gname = "back to Invalid (2)";
            7: tb_gname = "Invalid + local write -> Modified";
            8: tb_gname = "Modified + local read -> stays Modified";
            9: tb_gname = "Modified + local write -> stays Modified";
            10: tb_gname = "back to Invalid (3)";
            11: tb_gname = "get to Shared";
            12: tb_gname = "Shared + local write -> Modified";
            13: tb_gname = "back to Invalid (4)";
            14: tb_gname = "get to Exclusive";
            15: tb_gname = "Exclusive + bus_rd -> Shared, no writeback";
            16: tb_gname = "back to Invalid (5)";
            17: tb_gname = "get to Modified";
            18: tb_gname = "Modified + bus_rd -> Shared, writeback asserted";
            19: tb_gname = "back to Modified";
            20: tb_gname = "Modified + bus_rdx -> Invalid, writeback asserted";
            21: tb_gname = "back to Invalid (6)";
            22: tb_gname = "get to Shared (2)";
            23: tb_gname = "Shared + bus_rdx -> Invalid, no writeback";
            24: tb_gname = "get to Shared (3)";
            25: tb_gname = "Shared + bus_rd -> stays Shared";
            26: tb_gname = "back to Invalid (7)";
            27: tb_gname = "Invalid + bus_rd -> stays Invalid";
            28: tb_gname = "Invalid + bus_rdx -> stays Invalid";
            29: tb_gname = "reset before random run";
            30: tb_gname = "400 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((state ^ e_state) & m_state) !== 0) ||
                (((wb ^ e_wb) & m_wb) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h pr_rd=%h pr_wr=%h bus_rd=%h bus_rdx=%h shared_in=%h -> expected state=%h wb=%h, got state=%h wb=%h",
                             tb_vec, $time, rst, pr_rd, pr_wr, bus_rd, bus_rdx, shared_in, e_state, e_wb, state, wb);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, pr_rd, pr_wr, bus_rd, bus_rdx, shared_in, e_state, m_state, e_wb, m_wb) == 11) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 430)
            $display("FAIL: testbench read %0d of 430 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #5300;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
