-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal clk : std_logic := '0';
    signal rst : std_logic := '0';
    signal pr_rd : std_logic := '0';
    signal pr_wr : std_logic := '0';
    signal bus_rd : std_logic := '0';
    signal bus_rdx : std_logic := '0';
    signal shared_in : std_logic := '0';
    signal state : std_logic_vector(1 downto 0);
    signal wb : std_logic;
    signal tb_done : boolean := false;
begin
    dut : entity work.mesi_line
        port map (clk => clk, rst => rst, pr_rd => pr_rd, pr_wr => pr_wr, bus_rd => bus_rd, bus_rdx => bus_rdx, shared_in => shared_in, state => state, wb => wb);

    clk <= not clk after 5 ns when not tb_done;

    watchdog : process
    begin
        wait for 5300 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_rst : std_logic_vector(0 downto 0);
        variable v_pr_rd : std_logic_vector(0 downto 0);
        variable v_pr_wr : std_logic_vector(0 downto 0);
        variable v_bus_rd : std_logic_vector(0 downto 0);
        variable v_bus_rdx : std_logic_vector(0 downto 0);
        variable v_shared_in : std_logic_vector(0 downto 0);
        variable e_state, m_state : std_logic_vector(1 downto 0);
        variable e_wb, m_wb : std_logic_vector(0 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "reset goes to Invalid";
                when 1 => return "Invalid + local read, not shared -> Exclusive";
                when 2 => return "Exclusive + local read -> stays Exclusive";
                when 3 => return "back to Invalid";
                when 4 => return "Invalid + local read, shared -> Shared";
                when 5 => return "Shared + local read -> stays Shared";
                when 6 => return "back to Invalid (2)";
                when 7 => return "Invalid + local write -> Modified";
                when 8 => return "Modified + local read -> stays Modified";
                when 9 => return "Modified + local write -> stays Modified";
                when 10 => return "back to Invalid (3)";
                when 11 => return "get to Shared";
                when 12 => return "Shared + local write -> Modified";
                when 13 => return "back to Invalid (4)";
                when 14 => return "get to Exclusive";
                when 15 => return "Exclusive + bus_rd -> Shared, no writeback";
                when 16 => return "back to Invalid (5)";
                when 17 => return "get to Modified";
                when 18 => return "Modified + bus_rd -> Shared, writeback asserted";
                when 19 => return "back to Modified";
                when 20 => return "Modified + bus_rdx -> Invalid, writeback asserted";
                when 21 => return "back to Invalid (6)";
                when 22 => return "get to Shared (2)";
                when 23 => return "Shared + bus_rdx -> Invalid, no writeback";
                when 24 => return "get to Shared (3)";
                when 25 => return "Shared + bus_rd -> stays Shared";
                when 26 => return "back to Invalid (7)";
                when 27 => return "Invalid + bus_rd -> stays Invalid";
                when 28 => return "Invalid + bus_rdx -> stays Invalid";
                when 29 => return "reset before random run";
                when 30 => return "400 random cycles";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait until falling_edge(clk);
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_rst);
            hread(tb_l, v_pr_rd);
            hread(tb_l, v_pr_wr);
            hread(tb_l, v_bus_rd);
            hread(tb_l, v_bus_rdx);
            hread(tb_l, v_shared_in);
            hread(tb_l, e_state);
            hread(tb_l, m_state);
            hread(tb_l, e_wb);
            hread(tb_l, m_wb);
            rst <= v_rst(0);
            pr_rd <= v_pr_rd(0);
            pr_wr <= v_pr_wr(0);
            bus_rd <= v_bus_rd(0);
            bus_rdx <= v_bus_rdx(0);
            shared_in <= v_shared_in(0);
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait until falling_edge(clk);
            tb_bad := tb_diff(sv(state), e_state, m_state)
                   or tb_diff(sv(wb), e_wb, m_wb);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "rst=" & to_hstring(v_rst) & " " & "pr_rd=" & to_hstring(v_pr_rd) & " " & "pr_wr=" & to_hstring(v_pr_wr) & " " & "bus_rd=" & to_hstring(v_bus_rd) & " " & "bus_rdx=" & to_hstring(v_bus_rdx) & " " & "shared_in=" & to_hstring(v_shared_in) &
                        " -> expected " & "state=" & to_hstring(e_state) & " " & "wb=" & to_hstring(e_wb) &
                        ", got " & "state=" & to_hstring(sv(state)) & " " & "wb=" & to_hstring(sv(wb)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 430 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 430 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
