// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg sleep_req;
    reg wake_req;
    reg pwr_ack;
    wire clk_en;
    reg e_clk_en, m_clk_en;
    wire iso_en;
    reg e_iso_en, m_iso_en;
    wire save;
    reg e_save, m_save;
    wire restore;
    reg e_restore, m_restore;
    wire pwr_en;
    reg e_pwr_en, m_pwr_en;
    wire asleep;
    reg e_asleep, m_asleep;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    pwr_seq dut (.clk(clk), .rst(rst), .sleep_req(sleep_req), .wake_req(wake_req), .pwr_ack(pwr_ack), .clk_en(clk_en), .iso_en(iso_en), .save(save), .restore(restore), .pwr_en(pwr_en), .asleep(asleep));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "power-down sequence";
            1: tb_gname = "ignores sleep while off";
            2: tb_gname = "power-up sequence";
            3: tb_gname = "ignores wake while on";
            4: tb_gname = "3000 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((clk_en ^ e_clk_en) & m_clk_en) !== 0) ||
                (((iso_en ^ e_iso_en) & m_iso_en) !== 0) ||
                (((save ^ e_save) & m_save) !== 0) ||
                (((restore ^ e_restore) & m_restore) !== 0) ||
                (((pwr_en ^ e_pwr_en) & m_pwr_en) !== 0) ||
                (((asleep ^ e_asleep) & m_asleep) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h sleep_req=%h wake_req=%h pwr_ack=%h -> expected clk_en=%h iso_en=%h save=%h restore=%h pwr_en=%h asleep=%h, got clk_en=%h iso_en=%h save=%h restore=%h pwr_en=%h asleep=%h",
                             tb_vec, $time, rst, sleep_req, wake_req, pwr_ack, e_clk_en, e_iso_en, e_save, e_restore, e_pwr_en, e_asleep, clk_en, iso_en, save, restore, pwr_en, asleep);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, sleep_req, wake_req, pwr_ack, e_clk_en, m_clk_en, e_iso_en, m_iso_en, e_save, m_save, e_restore, m_restore, e_pwr_en, m_pwr_en, e_asleep, m_asleep) == 17) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3028)
            $display("FAIL: testbench read %0d of 3028 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #31280;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
