// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg in_valid;
    reg [7:0] in_data;
    wire out_valid;
    reg e_out_valid, m_out_valid;
    wire [7:0] out_data;
    reg [7:0] e_out_data, m_out_data;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    gated_pipe dut (.clk(clk), .rst(rst), .in_valid(in_valid), .in_data(in_data), .out_valid(out_valid), .out_data(out_data));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "results after 3 cycles";
            1: tb_gname = "bubbles don't toggle data";
            2: tb_gname = "2500 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((out_valid ^ e_out_valid) & m_out_valid) !== 0) ||
                (((out_data ^ e_out_data) & m_out_data) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h in_valid=%h in_data=%h -> expected out_valid=%h out_data=%h, got out_valid=%h out_data=%h",
                             tb_vec, $time, rst, in_valid, in_data, e_out_valid, e_out_data, out_valid, out_data);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h\n", tb_grp, rst, in_valid, in_data, e_out_valid, m_out_valid, e_out_data, m_out_data) == 8) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 2516)
            $display("FAIL: testbench read %0d of 2516 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #26160;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
