// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    logic clk = 1'b0;
    logic rst = 1'b1;
    logic valid = '0;
    logic [7:0] temp = '0;
    int trace;

    chk_range dut (.clk(clk), .rst(rst), .valid(valid), .temp(temp));

    always #5 clk = ~clk;

    initial begin
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        if (!$value$plusargs("trace=%d", trace)) trace = 0;
        case (trace)
            0: begin
                @(negedge clk); rst = 1'd1; valid = 1'd0; temp = 8'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); valid = 1'd1; temp = 8'd10;
                @(negedge clk); temp = 8'd55;
                @(negedge clk); temp = 8'd90;
            end
            1: begin
                @(negedge clk); rst = 1'd1; valid = 1'd0; temp = 8'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); valid = 1'd1; temp = 8'd50;
                @(negedge clk); temp = 8'd91;
                @(negedge clk); valid = 1'd0; temp = 8'd0;
            end
            2: begin
                @(negedge clk); rst = 1'd1; valid = 1'd0; temp = 8'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); valid = 1'd1; temp = 8'd9;
            end
            3: begin
                @(negedge clk); rst = 1'd1; valid = 1'd0; temp = 8'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0; temp = 8'd200;
                @(negedge clk); valid = 1'd1; temp = 8'd20;
                @(negedge clk); valid = 1'd0; temp = 8'd5;
                @(negedge clk); valid = 1'd1; temp = 8'd30;
            end
            default: ;
        endcase
        repeat (3) @(negedge clk);
        $display("TRACE_DONE");
        $finish;
    end
endmodule
