-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal addr : std_logic_vector(31 downto 0) := (others => '0');
    signal valid : std_logic_vector(3 downto 0) := (others => '0');
    signal conflict : std_logic;
    signal cycles : std_logic_vector(2 downto 0);
    signal tb_done : boolean := false;
begin
    dut : entity work.bank_conflict
        port map (addr => addr, valid => valid, conflict => conflict, cycles => cycles);

    watchdog : process
    begin
        wait for 31140 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_addr : std_logic_vector(31 downto 0);
        variable v_valid : std_logic_vector(3 downto 0);
        variable e_conflict, m_conflict : std_logic_vector(0 downto 0);
        variable e_cycles, m_cycles : std_logic_vector(2 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "no conflict";
                when 1 => return "broadcast (same word) is not a conflict";
                when 2 => return "conflicts";
                when 3 => return "inactive lanes are ignored";
                when 4 => return "3000 random accesses";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait for 1 ns;
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_addr);
            hread(tb_l, v_valid);
            hread(tb_l, e_conflict);
            hread(tb_l, m_conflict);
            hread(tb_l, e_cycles);
            hread(tb_l, m_cycles);
            addr <= v_addr;
            valid <= v_valid;
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait for 5 ns;
            tb_bad := tb_diff(sv(conflict), e_conflict, m_conflict)
                   or tb_diff(sv(cycles), e_cycles, m_cycles);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "addr=" & to_hstring(v_addr) & " " & "valid=" & to_hstring(v_valid) &
                        " -> expected " & "conflict=" & to_hstring(e_conflict) & " " & "cycles=" & to_hstring(e_cycles) &
                        ", got " & "conflict=" & to_hstring(sv(conflict)) & " " & "cycles=" & to_hstring(sv(cycles)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
            wait for 5 ns;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 3014 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 3014 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
