// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg tick_ms;
    reg load;
    reg [9:0] ld_ms;
    reg [5:0] ld_sec;
    reg [5:0] ld_min;
    reg [4:0] ld_hr;
    wire [9:0] ms;
    reg [9:0] e_ms, m_ms;
    wire [5:0] sec;
    reg [5:0] e_sec, m_sec;
    wire [5:0] min;
    reg [5:0] e_min, m_min;
    wire [4:0] hr;
    reg [4:0] e_hr, m_hr;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    time_counter dut (.clk(clk), .rst(rst), .tick_ms(tick_ms), .load(load), .ld_ms(ld_ms), .ld_sec(ld_sec), .ld_min(ld_min), .ld_hr(ld_hr), .ms(ms), .sec(sec), .min(min), .hr(hr));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "counting milliseconds";
            1: tb_gname = "rollover of seconds";
            2: tb_gname = "rollover of minutes and hours";
            3: tb_gname = "rollover of the day";
            4: tb_gname = "load";
            5: tb_gname = "1500 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((ms ^ e_ms) & m_ms) !== 0) ||
                (((sec ^ e_sec) & m_sec) !== 0) ||
                (((min ^ e_min) & m_min) !== 0) ||
                (((hr ^ e_hr) & m_hr) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h tick_ms=%h load=%h ld_ms=%h ld_sec=%h ld_min=%h ld_hr=%h -> expected ms=%h sec=%h min=%h hr=%h, got ms=%h sec=%h min=%h hr=%h",
                             tb_vec, $time, rst, tick_ms, load, ld_ms, ld_sec, ld_min, ld_hr, e_ms, e_sec, e_min, e_hr, ms, sec, min, hr);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, tick_ms, load, ld_ms, ld_sec, ld_min, ld_hr, e_ms, m_ms, e_sec, m_sec, e_min, m_min, e_hr, m_hr) == 16) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 1531)
            $display("FAIL: testbench read %0d of 1531 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #16310;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
