-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal clk : std_logic := '0';
    signal rst : std_logic := '0';
    signal tick_ms : std_logic := '0';
    signal load : std_logic := '0';
    signal ld_ms : std_logic_vector(9 downto 0) := (others => '0');
    signal ld_sec : std_logic_vector(5 downto 0) := (others => '0');
    signal ld_min : std_logic_vector(5 downto 0) := (others => '0');
    signal ld_hr : std_logic_vector(4 downto 0) := (others => '0');
    signal ms : std_logic_vector(9 downto 0);
    signal sec : std_logic_vector(5 downto 0);
    signal min : std_logic_vector(5 downto 0);
    signal hr : std_logic_vector(4 downto 0);
    signal tb_done : boolean := false;
begin
    dut : entity work.time_counter
        port map (clk => clk, rst => rst, tick_ms => tick_ms, load => load, ld_ms => ld_ms, ld_sec => ld_sec, ld_min => ld_min, ld_hr => ld_hr, ms => ms, sec => sec, min => min, hr => hr);

    clk <= not clk after 5 ns when not tb_done;

    watchdog : process
    begin
        wait for 16310 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_rst : std_logic_vector(0 downto 0);
        variable v_tick_ms : std_logic_vector(0 downto 0);
        variable v_load : std_logic_vector(0 downto 0);
        variable v_ld_ms : std_logic_vector(9 downto 0);
        variable v_ld_sec : std_logic_vector(5 downto 0);
        variable v_ld_min : std_logic_vector(5 downto 0);
        variable v_ld_hr : std_logic_vector(4 downto 0);
        variable e_ms, m_ms : std_logic_vector(9 downto 0);
        variable e_sec, m_sec : std_logic_vector(5 downto 0);
        variable e_min, m_min : std_logic_vector(5 downto 0);
        variable e_hr, m_hr : std_logic_vector(4 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "counting milliseconds";
                when 1 => return "rollover of seconds";
                when 2 => return "rollover of minutes and hours";
                when 3 => return "rollover of the day";
                when 4 => return "load";
                when 5 => return "1500 random cycles";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait until falling_edge(clk);
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_rst);
            hread(tb_l, v_tick_ms);
            hread(tb_l, v_load);
            hread(tb_l, v_ld_ms);
            hread(tb_l, v_ld_sec);
            hread(tb_l, v_ld_min);
            hread(tb_l, v_ld_hr);
            hread(tb_l, e_ms);
            hread(tb_l, m_ms);
            hread(tb_l, e_sec);
            hread(tb_l, m_sec);
            hread(tb_l, e_min);
            hread(tb_l, m_min);
            hread(tb_l, e_hr);
            hread(tb_l, m_hr);
            rst <= v_rst(0);
            tick_ms <= v_tick_ms(0);
            load <= v_load(0);
            ld_ms <= v_ld_ms;
            ld_sec <= v_ld_sec;
            ld_min <= v_ld_min;
            ld_hr <= v_ld_hr;
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait until falling_edge(clk);
            tb_bad := tb_diff(sv(ms), e_ms, m_ms)
                   or tb_diff(sv(sec), e_sec, m_sec)
                   or tb_diff(sv(min), e_min, m_min)
                   or tb_diff(sv(hr), e_hr, m_hr);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "rst=" & to_hstring(v_rst) & " " & "tick_ms=" & to_hstring(v_tick_ms) & " " & "load=" & to_hstring(v_load) & " " & "ld_ms=" & to_hstring(v_ld_ms) & " " & "ld_sec=" & to_hstring(v_ld_sec) & " " & "ld_min=" & to_hstring(v_ld_min) & " " & "ld_hr=" & to_hstring(v_ld_hr) &
                        " -> expected " & "ms=" & to_hstring(e_ms) & " " & "sec=" & to_hstring(e_sec) & " " & "min=" & to_hstring(e_min) & " " & "hr=" & to_hstring(e_hr) &
                        ", got " & "ms=" & to_hstring(sv(ms)) & " " & "sec=" & to_hstring(sv(sec)) & " " & "min=" & to_hstring(sv(min)) & " " & "hr=" & to_hstring(sv(hr)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 1531 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 1531 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
