// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg en;
    reg op;
    reg [7:0] a;
    reg [7:0] b;
    wire [15:0] y;
    reg [15:0] e_y, m_y;
    wire [15:0] add_in;
    reg [15:0] e_add_in, m_add_in;
    wire [15:0] mul_in;
    reg [15:0] e_mul_in, m_mul_in;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    iso_alu dut (.clk(clk), .rst(rst), .en(en), .op(op), .a(a), .b(b), .y(y), .add_in(add_in), .mul_in(mul_in));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "results";
            1: tb_gname = "unused unit's operands hold";
            2: tb_gname = "disabled holds everything";
            3: tb_gname = "3000 random cycles";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((y ^ e_y) & m_y) !== 0) ||
                (((add_in ^ e_add_in) & m_add_in) !== 0) ||
                (((mul_in ^ e_mul_in) & m_mul_in) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h en=%h op=%h a=%h b=%h -> expected y=%h add_in=%h mul_in=%h, got y=%h add_in=%h mul_in=%h",
                             tb_vec, $time, rst, en, op, a, b, e_y, e_add_in, e_mul_in, y, add_in, mul_in);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, en, op, a, b, e_y, m_y, e_add_in, m_add_in, e_mul_in, m_mul_in) == 12) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3011)
            $display("FAIL: testbench read %0d of 3011 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #31110;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
