-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal clk : std_logic := '0';
    signal rst : std_logic := '0';
    signal en : std_logic := '0';
    signal op : std_logic := '0';
    signal a : std_logic_vector(7 downto 0) := (others => '0');
    signal b : std_logic_vector(7 downto 0) := (others => '0');
    signal y : std_logic_vector(15 downto 0);
    signal add_in : std_logic_vector(15 downto 0);
    signal mul_in : std_logic_vector(15 downto 0);
    signal tb_done : boolean := false;
begin
    dut : entity work.iso_alu
        port map (clk => clk, rst => rst, en => en, op => op, a => a, b => b, y => y, add_in => add_in, mul_in => mul_in);

    clk <= not clk after 5 ns when not tb_done;

    watchdog : process
    begin
        wait for 31110 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_rst : std_logic_vector(0 downto 0);
        variable v_en : std_logic_vector(0 downto 0);
        variable v_op : std_logic_vector(0 downto 0);
        variable v_a : std_logic_vector(7 downto 0);
        variable v_b : std_logic_vector(7 downto 0);
        variable e_y, m_y : std_logic_vector(15 downto 0);
        variable e_add_in, m_add_in : std_logic_vector(15 downto 0);
        variable e_mul_in, m_mul_in : std_logic_vector(15 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "results";
                when 1 => return "unused unit's operands hold";
                when 2 => return "disabled holds everything";
                when 3 => return "3000 random cycles";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait until falling_edge(clk);
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_rst);
            hread(tb_l, v_en);
            hread(tb_l, v_op);
            hread(tb_l, v_a);
            hread(tb_l, v_b);
            hread(tb_l, e_y);
            hread(tb_l, m_y);
            hread(tb_l, e_add_in);
            hread(tb_l, m_add_in);
            hread(tb_l, e_mul_in);
            hread(tb_l, m_mul_in);
            rst <= v_rst(0);
            en <= v_en(0);
            op <= v_op(0);
            a <= v_a;
            b <= v_b;
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait until falling_edge(clk);
            tb_bad := tb_diff(sv(y), e_y, m_y)
                   or tb_diff(sv(add_in), e_add_in, m_add_in)
                   or tb_diff(sv(mul_in), e_mul_in, m_mul_in);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "rst=" & to_hstring(v_rst) & " " & "en=" & to_hstring(v_en) & " " & "op=" & to_hstring(v_op) & " " & "a=" & to_hstring(v_a) & " " & "b=" & to_hstring(v_b) &
                        " -> expected " & "y=" & to_hstring(e_y) & " " & "add_in=" & to_hstring(e_add_in) & " " & "mul_in=" & to_hstring(e_mul_in) &
                        ", got " & "y=" & to_hstring(sv(y)) & " " & "add_in=" & to_hstring(sv(add_in)) & " " & "mul_in=" & to_hstring(sv(mul_in)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 3011 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 3011 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
