// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    logic clk = 1'b0;
    logic rst = 1'b1;
    logic valid = '0;
    logic ready = '0;
    logic [1:0] size = '0;
    logic [7:0] addr = '0;
    int trace;

    chk_align dut (.clk(clk), .rst(rst), .valid(valid), .ready(ready), .size(size), .addr(addr));

    always #5 clk = ~clk;

    initial begin
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        if (!$value$plusargs("trace=%d", trace)) trace = 0;
        case (trace)
            0: begin
                @(negedge clk); rst = 1'd1; valid = 1'd0; ready = 1'd0; size = 2'd0; addr = 8'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); valid = 1'd1; ready = 1'd1; size = 2'd2; addr = 8'd64;
                @(negedge clk); size = 2'd1; addr = 8'd66;
                @(negedge clk); size = 2'd0; addr = 8'd67;
            end
            1: begin
                @(negedge clk); rst = 1'd1; valid = 1'd0; ready = 1'd0; size = 2'd0; addr = 8'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); valid = 1'd1; ready = 1'd1; size = 2'd2; addr = 8'd65;
            end
            2: begin
                @(negedge clk); rst = 1'd1; valid = 1'd0; ready = 1'd0; size = 2'd0; addr = 8'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); valid = 1'd1; ready = 1'd1; size = 2'd1; addr = 8'd19;
            end
            3: begin
                @(negedge clk); rst = 1'd1; valid = 1'd0; ready = 1'd0; size = 2'd0; addr = 8'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); valid = 1'd1; ready = 1'd1; size = 2'd3;
            end
            4: begin
                @(negedge clk); rst = 1'd1; valid = 1'd0; ready = 1'd0; size = 2'd0; addr = 8'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); valid = 1'd1; size = 2'd2; addr = 8'd64;
                @(negedge clk); addr = 8'd68;
                @(negedge clk); ready = 1'd1;
            end
            5: begin
                @(negedge clk); rst = 1'd1; valid = 1'd0; ready = 1'd0; size = 2'd0; addr = 8'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); valid = 1'd1; size = 2'd2; addr = 8'd128;
                @(negedge clk); 
                @(negedge clk); ready = 1'd1;
                @(negedge clk); valid = 1'd0; ready = 1'd0; size = 2'd0; addr = 8'd51;
            end
            default: ;
        endcase
        repeat (3) @(negedge clk);
        $display("TRACE_DONE");
        $finish;
    end
endmodule
