-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal clk : std_logic := '0';
    signal rst : std_logic := '0';
    signal issue : std_logic := '0';
    signal fu : std_logic_vector(1 downto 0) := (others => '0');
    signal latency : std_logic_vector(2 downto 0) := (others => '0');
    signal busy : std_logic_vector(3 downto 0);
    signal accepted : std_logic;
    signal tb_done : boolean := false;
begin
    dut : entity work.fu_tracker
        port map (clk => clk, rst => rst, issue => issue, fu => fu, latency => latency, busy => busy, accepted => accepted);

    clk <= not clk after 5 ns when not tb_done;

    watchdog : process
    begin
        wait for 26240 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_rst : std_logic_vector(0 downto 0);
        variable v_issue : std_logic_vector(0 downto 0);
        variable v_fu : std_logic_vector(1 downto 0);
        variable v_latency : std_logic_vector(2 downto 0);
        variable e_busy, m_busy : std_logic_vector(3 downto 0);
        variable e_accepted, m_accepted : std_logic_vector(0 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "issue and count down";
                when 1 => return "structural hazard: busy unit rejects";
                when 2 => return "independent units";
                when 3 => return "latency 0 is rejected";
                when 4 => return "2500 random issues";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait until falling_edge(clk);
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_rst);
            hread(tb_l, v_issue);
            hread(tb_l, v_fu);
            hread(tb_l, v_latency);
            hread(tb_l, e_busy);
            hread(tb_l, m_busy);
            hread(tb_l, e_accepted);
            hread(tb_l, m_accepted);
            rst <= v_rst(0);
            issue <= v_issue(0);
            fu <= v_fu;
            latency <= v_latency;
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait until falling_edge(clk);
            tb_bad := tb_diff(sv(busy), e_busy, m_busy)
                   or tb_diff(sv(accepted), e_accepted, m_accepted);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "rst=" & to_hstring(v_rst) & " " & "issue=" & to_hstring(v_issue) & " " & "fu=" & to_hstring(v_fu) & " " & "latency=" & to_hstring(v_latency) &
                        " -> expected " & "busy=" & to_hstring(e_busy) & " " & "accepted=" & to_hstring(e_accepted) &
                        ", got " & "busy=" & to_hstring(sv(busy)) & " " & "accepted=" & to_hstring(sv(accepted)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 2524 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 2524 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
