// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg [31:0] instr;
    wire [2:0] fmt;
    reg [2:0] e_fmt, m_fmt;
    wire [31:0] imm;
    reg [31:0] e_imm, m_imm;
    wire reg_write;
    reg e_reg_write, m_reg_write;
    wire mem_read;
    reg e_mem_read, m_mem_read;
    wire mem_write;
    reg e_mem_write, m_mem_write;
    wire branch;
    reg e_branch, m_branch;
    wire jump;
    reg e_jump, m_jump;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    rv32i_decode dut (.instr(instr), .fmt(fmt), .imm(imm), .reg_write(reg_write), .mem_read(mem_read), .mem_write(mem_write), .branch(branch), .jump(jump));

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "R-type";
            1: tb_gname = "I-type (OP-IMM, LOAD, JALR)";
            2: tb_gname = "S-type";
            3: tb_gname = "B-type";
            4: tb_gname = "U-type";
            5: tb_gname = "J-type";
            6: tb_gname = "unknown opcodes";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((fmt ^ e_fmt) & m_fmt) !== 0) ||
                (((imm ^ e_imm) & m_imm) !== 0) ||
                (((reg_write ^ e_reg_write) & m_reg_write) !== 0) ||
                (((mem_read ^ e_mem_read) & m_mem_read) !== 0) ||
                (((mem_write ^ e_mem_write) & m_mem_write) !== 0) ||
                (((branch ^ e_branch) & m_branch) !== 0) ||
                (((jump ^ e_jump) & m_jump) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): instr=%h -> expected fmt=%h imm=%h reg_write=%h mem_read=%h mem_write=%h branch=%h jump=%h, got fmt=%h imm=%h reg_write=%h mem_read=%h mem_write=%h branch=%h jump=%h",
                             tb_vec, $time, instr, e_fmt, e_imm, e_reg_write, e_mem_read, e_mem_write, e_branch, e_jump, fmt, imm, reg_write, mem_read, mem_write, branch, jump);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        #1;
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, instr, e_fmt, m_fmt, e_imm, m_imm, e_reg_write, m_reg_write, e_mem_read, m_mem_read, e_mem_write, m_mem_write, e_branch, m_branch, e_jump, m_jump) == 16) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            #5;
            tb_check;
            #5;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 2712)
            $display("FAIL: testbench read %0d of 2712 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #28120;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
