-- Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb is
end entity;

architecture sim of tb is
    signal instr : std_logic_vector(31 downto 0) := (others => '0');
    signal fmt : std_logic_vector(2 downto 0);
    signal imm : std_logic_vector(31 downto 0);
    signal reg_write : std_logic;
    signal mem_read : std_logic;
    signal mem_write : std_logic;
    signal branch : std_logic;
    signal jump : std_logic;
    signal tb_done : boolean := false;
begin
    dut : entity work.rv32i_decode
        port map (instr => instr, fmt => fmt, imm => imm, reg_write => reg_write, mem_read => mem_read, mem_write => mem_write, branch => branch, jump => jump);

    watchdog : process
    begin
        wait for 28120 ns;
        report "FAIL: testbench watchdog expired";
        std.env.finish;
        wait;
    end process;

    stim : process
        file tb_f : text open read_mode is "vectors.txt";
        variable tb_l, tb_detail : line;
        variable tb_grp : integer;
        variable tb_cur : integer := -1;
        variable tb_errors, tb_vec : natural := 0;
        variable tb_bad : boolean;
        variable v_instr : std_logic_vector(31 downto 0);
        variable e_fmt, m_fmt : std_logic_vector(2 downto 0);
        variable e_imm, m_imm : std_logic_vector(31 downto 0);
        variable e_reg_write, m_reg_write : std_logic_vector(0 downto 0);
        variable e_mem_read, m_mem_read : std_logic_vector(0 downto 0);
        variable e_mem_write, m_mem_write : std_logic_vector(0 downto 0);
        variable e_branch, m_branch : std_logic_vector(0 downto 0);
        variable e_jump, m_jump : std_logic_vector(0 downto 0);

        function tb_gname(g : integer) return string is
        begin
            case g is
                when 0 => return "R-type";
                when 1 => return "I-type (OP-IMM, LOAD, JALR)";
                when 2 => return "S-type";
                when 3 => return "B-type";
                when 4 => return "U-type";
                when 5 => return "J-type";
                when 6 => return "unknown opcodes";
                when others => return "?";
            end case;
        end function;

        function tb_diff(got, exp, mask : std_logic_vector) return boolean is
            alias g : std_logic_vector(got'length - 1 downto 0) is got;
            alias e : std_logic_vector(exp'length - 1 downto 0) is exp;
            alias m : std_logic_vector(mask'length - 1 downto 0) is mask;
        begin
            for i in e'range loop
                if m(i) = '1' and g(i) /= e(i) then
                    return true;
                end if;
            end loop;
            return false;
        end function;

        procedure tb_end_group is
        begin
            if tb_errors = 0 then
                report "PASS: " & tb_gname(tb_cur);
            else
                report "FAIL: " & tb_gname(tb_cur) & " -- " & tb_detail.all & " (" &
                       integer'image(tb_errors) & " mismatches)";
            end if;
        end procedure;

        function sv(s : std_logic) return std_logic_vector is
        begin
            return (0 => s);
        end function;
        function sv(s : std_logic_vector) return std_logic_vector is
        begin
            return s;
        end function;
    begin
        wait for 1 ns;
        while not endfile(tb_f) loop
            readline(tb_f, tb_l);
            next when tb_l'length = 0;
            read(tb_l, tb_grp);
            hread(tb_l, v_instr);
            hread(tb_l, e_fmt);
            hread(tb_l, m_fmt);
            hread(tb_l, e_imm);
            hread(tb_l, m_imm);
            hread(tb_l, e_reg_write);
            hread(tb_l, m_reg_write);
            hread(tb_l, e_mem_read);
            hread(tb_l, m_mem_read);
            hread(tb_l, e_mem_write);
            hread(tb_l, m_mem_write);
            hread(tb_l, e_branch);
            hread(tb_l, m_branch);
            hread(tb_l, e_jump);
            hread(tb_l, m_jump);
            instr <= v_instr;
            if tb_grp /= tb_cur then
                if tb_cur >= 0 then
                    tb_end_group;
                end if;
                tb_cur := tb_grp;
                tb_errors := 0;
                deallocate(tb_detail);
                tb_detail := new string'("");
            end if;
            wait for 5 ns;
            tb_bad := tb_diff(sv(fmt), e_fmt, m_fmt)
                   or tb_diff(sv(imm), e_imm, m_imm)
                   or tb_diff(sv(reg_write), e_reg_write, m_reg_write)
                   or tb_diff(sv(mem_read), e_mem_read, m_mem_read)
                   or tb_diff(sv(mem_write), e_mem_write, m_mem_write)
                   or tb_diff(sv(branch), e_branch, m_branch)
                   or tb_diff(sv(jump), e_jump, m_jump);
            if tb_bad then
                if tb_errors = 0 then
                    deallocate(tb_detail);
                    tb_detail := new string'("vector " & integer'image(tb_vec) & " (t=" & time'image(now) & "): " &
                        "instr=" & to_hstring(v_instr) &
                        " -> expected " & "fmt=" & to_hstring(e_fmt) & " " & "imm=" & to_hstring(e_imm) & " " & "reg_write=" & to_hstring(e_reg_write) & " " & "mem_read=" & to_hstring(e_mem_read) & " " & "mem_write=" & to_hstring(e_mem_write) & " " & "branch=" & to_hstring(e_branch) & " " & "jump=" & to_hstring(e_jump) &
                        ", got " & "fmt=" & to_hstring(sv(fmt)) & " " & "imm=" & to_hstring(sv(imm)) & " " & "reg_write=" & to_hstring(sv(reg_write)) & " " & "mem_read=" & to_hstring(sv(mem_read)) & " " & "mem_write=" & to_hstring(sv(mem_write)) & " " & "branch=" & to_hstring(sv(branch)) & " " & "jump=" & to_hstring(sv(jump)));
                end if;
                tb_errors := tb_errors + 1;
            end if;
            tb_vec := tb_vec + 1;
            wait for 5 ns;
        end loop;
        if tb_cur >= 0 then
            tb_end_group;
        end if;
        if tb_vec /= 2712 then
            report "FAIL: testbench read " & integer'image(tb_vec) & " of 2712 vectors";
        end if;
        report "TB_DONE";
        tb_done <= true;
        std.env.finish;
        wait;
    end process;
end architecture;
