// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg miss_valid;
    reg [7:0] miss_addr;
    reg resp_valid;
    reg [1:0] resp_id;
    wire mem_req;
    reg e_mem_req, m_mem_req;
    wire [1:0] mem_id;
    reg [1:0] e_mem_id, m_mem_id;
    wire [7:0] mem_addr;
    reg [7:0] e_mem_addr, m_mem_addr;
    wire merged;
    reg e_merged, m_merged;
    wire [1:0] merge_id;
    reg [1:0] e_merge_id, m_merge_id;
    wire stall;
    reg e_stall, m_stall;
    wire [3:0] valid_mask;
    reg [3:0] e_valid_mask, m_valid_mask;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    mshr4 dut (.clk(clk), .rst(rst), .miss_valid(miss_valid), .miss_addr(miss_addr), .resp_valid(resp_valid), .resp_id(resp_id), .mem_req(mem_req), .mem_id(mem_id), .mem_addr(mem_addr), .merged(merged), .merge_id(merge_id), .stall(stall), .valid_mask(valid_mask));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "reset";
            1: tb_gname = "primary miss";
            2: tb_gname = "secondary miss merges";
            3: tb_gname = "fill all entries";
            4: tb_gname = "full: stall";
            5: tb_gname = "full: merge still works";
            6: tb_gname = "response frees an entry first";
            7: tb_gname = "3000 random misses and responses";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((mem_req ^ e_mem_req) & m_mem_req) !== 0) ||
                (((mem_id ^ e_mem_id) & m_mem_id) !== 0) ||
                (((mem_addr ^ e_mem_addr) & m_mem_addr) !== 0) ||
                (((merged ^ e_merged) & m_merged) !== 0) ||
                (((merge_id ^ e_merge_id) & m_merge_id) !== 0) ||
                (((stall ^ e_stall) & m_stall) !== 0) ||
                (((valid_mask ^ e_valid_mask) & m_valid_mask) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h miss_valid=%h miss_addr=%h resp_valid=%h resp_id=%h -> expected mem_req=%h mem_id=%h mem_addr=%h merged=%h merge_id=%h stall=%h valid_mask=%h, got mem_req=%h mem_id=%h mem_addr=%h merged=%h merge_id=%h stall=%h valid_mask=%h",
                             tb_vec, $time, rst, miss_valid, miss_addr, resp_valid, resp_id, e_mem_req, e_mem_id, e_mem_addr, e_merged, e_merge_id, e_stall, e_valid_mask, mem_req, mem_id, mem_addr, merged, merge_id, stall, valid_mask);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h\n", tb_grp, rst, miss_valid, miss_addr, resp_valid, resp_id, e_mem_req, m_mem_req, e_mem_id, m_mem_id, e_mem_addr, m_mem_addr, e_merged, m_merged, e_merge_id, m_merge_id, e_stall, m_stall, e_valid_mask, m_valid_mask) == 20) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 3011)
            $display("FAIL: testbench read %0d of 3011 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #31110;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
