// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg din;
    wire level;
    reg e_level, m_level;
    wire rise;
    reg e_rise, m_rise;
    wire fall;
    reg e_fall, m_fall;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    sync_edge dut (.clk(clk), .rst(rst), .din(din), .level(level), .rise(rise), .fall(fall));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "rising edge";
            1: tb_gname = "falling edge";
            2: tb_gname = "short pulses";
            3: tb_gname = "1500 random samples";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((level ^ e_level) & m_level) !== 0) ||
                (((rise ^ e_rise) & m_rise) !== 0) ||
                (((fall ^ e_fall) & m_fall) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h din=%h -> expected level=%h rise=%h fall=%h, got level=%h rise=%h fall=%h",
                             tb_vec, $time, rst, din, e_level, e_rise, e_fall, level, rise, fall);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h %h\n", tb_grp, rst, din, e_level, m_level, e_rise, m_rise, e_fall, m_fall) == 9) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 1518)
            $display("FAIL: testbench read %0d of 1518 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #16180;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
