// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    logic clk = 1'b0;
    logic rst = 1'b1;
    logic start = '0;
    logic done = '0;
    int trace;

    chk_precedence dut (.clk(clk), .rst(rst), .start(start), .done(done));

    always #5 clk = ~clk;

    initial begin
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        if (!$value$plusargs("trace=%d", trace)) trace = 0;
        case (trace)
            0: begin
                @(negedge clk); rst = 1'd1; start = 1'd0; done = 1'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); start = 1'd1;
                @(negedge clk); start = 1'd0;
                @(negedge clk); 
                @(negedge clk); done = 1'd1;
                @(negedge clk); done = 1'd0;
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
            end
            1: begin
                @(negedge clk); rst = 1'd1; start = 1'd0; done = 1'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); done = 1'd1;
                @(negedge clk); done = 1'd0;
                @(negedge clk); 
                @(negedge clk); 
            end
            2: begin
                @(negedge clk); rst = 1'd1; start = 1'd0; done = 1'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); start = 1'd1;
                @(negedge clk); start = 1'd0;
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); done = 1'd1;
            end
            3: begin
                @(negedge clk); rst = 1'd1; start = 1'd0; done = 1'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); start = 1'd1;
                @(negedge clk); start = 1'd0;
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); done = 1'd1;
                @(negedge clk); done = 1'd0;
            end
            4: begin
                @(negedge clk); rst = 1'd1; start = 1'd0; done = 1'd0;
                @(negedge clk); 
                @(negedge clk); rst = 1'd0;
                @(negedge clk); 
                @(negedge clk); start = 1'd1; done = 1'd1;
                @(negedge clk); start = 1'd0; done = 1'd0;
                @(negedge clk); 
                @(negedge clk); 
                @(negedge clk); 
            end
            default: ;
        endcase
        repeat (3) @(negedge clk);
        $display("TRACE_DONE");
        $finish;
    end
endmodule
