// Generated by `hwlc gen` from gen.py - edit gen.py, not this file.
`timescale 1ns/1ps
module tb;
    reg clk = 1'b0;
    reg rst;
    reg valid;
    reg [7:0] din;
    wire [7:0] wmin;
    reg [7:0] e_wmin, m_wmin;
    wire [7:0] wmax;
    reg [7:0] e_wmax, m_wmax;
    integer tb_fd, tb_grp, tb_cur, tb_errors, tb_vec;
    reg [8*400-1:0] tb_detail;

    win_minmax dut (.clk(clk), .rst(rst), .valid(valid), .din(din), .wmin(wmin), .wmax(wmax));

    always #5 clk = ~clk;

    function [8*120-1:0] tb_gname(input integer g);
        case (g)
            0: tb_gname = "fills the window";
            1: tb_gname = "maximum leaves the window";
            2: tb_gname = "holds without valid";
            3: tb_gname = "2500 random samples";
            default: tb_gname = "?";
        endcase
    endfunction

    function real tb_abs(input real x);
        tb_abs = x < 0.0 ? -x : x;
    endfunction

    task tb_end_group;
        begin
            if (tb_errors == 0) $display("PASS: %0s", tb_gname(tb_cur));
            else $display("FAIL: %0s -- %0s (%0d mismatches)", tb_gname(tb_cur), tb_detail, tb_errors);
        end
    endtask

    task tb_check;
        begin
            if ((((wmin ^ e_wmin) & m_wmin) !== 0) ||
                (((wmax ^ e_wmax) & m_wmax) !== 0)) begin
                if (tb_errors == 0)
                    $sformat(tb_detail, "vector %0d (t=%t): rst=%h valid=%h din=%h -> expected wmin=%h wmax=%h, got wmin=%h wmax=%h",
                             tb_vec, $time, rst, valid, din, e_wmin, e_wmax, wmin, wmax);
                tb_errors = tb_errors + 1;
            end
        end
    endtask

    initial begin
        $timeformat(-9, 0, " ns", 0);
        if ($test$plusargs("vcd")) begin
            $dumpfile("wave.vcd");
            $dumpvars(1, dut);
        end
        tb_fd = $fopen("vectors.txt", "r");
        if (tb_fd == 0) begin
            $display("FAIL: testbench could not open its vector file");
            $display("TB_DONE");
            $finish;
        end
        tb_cur = -1; tb_vec = 0; tb_errors = 0;
        @(negedge clk);
        while ($fscanf(tb_fd, "%d %h %h %h %h %h %h %h\n", tb_grp, rst, valid, din, e_wmin, m_wmin, e_wmax, m_wmax) == 8) begin
            if (tb_grp != tb_cur) begin
                if (tb_cur >= 0) tb_end_group;
                tb_cur = tb_grp; tb_errors = 0; tb_detail = "";
            end
            @(negedge clk);
            tb_check;
            tb_vec = tb_vec + 1;
        end
        if (tb_cur >= 0) tb_end_group;
        if (tb_vec != 2515)
            $display("FAIL: testbench read %0d of 2515 vectors", tb_vec);
        $display("TB_DONE");
        $finish;
    end

    initial begin
        #26150;
        $display("FAIL: testbench watchdog expired");
        $finish;
    end
endmodule
